// <auto-generated />
using System;
using Central_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Central_BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926022906_RenomeiaIndicesPkTb")]
    partial class RenomeiaIndicesPkTb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Central_BackEnd.Models.Acessos.AuditoriaAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAcesso");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Empresa");

                    b.Property<string>("EnderecoIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EnderecoIP");

                    b.Property<TimeSpan>("HoraAcesso")
                        .HasColumnType("time")
                        .HasColumnName("HoraAcesso");

                    b.Property<string>("Navegador")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Navegador");

                    b.Property<string>("TipoInformacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TipoInformacao");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Usuario");

                    b.HasKey("Id");

                    b.ToTable("tbauditoriaacesso");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Funcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FUNCAO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Classificacao")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CLASSIFICACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("tbfuncao");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.AgendaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AGD_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AGD_Cor");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("AGD_DataAlteracao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("AGD_DataFim");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("AGD_DataInclusao");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("AGD_DataInicio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("AGD_Descricao");

                    b.Property<bool>("DiaInteiro")
                        .HasColumnType("bit")
                        .HasColumnName("AGD_DiaInteiro");

                    b.Property<string>("Local")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AGD_Local");

                    b.Property<string>("OperadorId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("AGD_OperadorId");

                    b.Property<int>("PadraoRecorrencia")
                        .HasColumnType("int")
                        .HasColumnName("AGD_PadraoRecorrencia");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("AGD_Prioridade");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("int")
                        .HasColumnName("AGD_ProjetoId");

                    b.Property<bool>("Recorrente")
                        .HasColumnType("bit")
                        .HasColumnName("AGD_Recorrente");

                    b.Property<int?>("SLAMinutos")
                        .HasColumnType("int")
                        .HasColumnName("AGD_SLAMinutos");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("AGD_Tipo");

                    b.Property<int?>("TipoId")
                        .HasColumnType("int")
                        .HasColumnName("AGD_TipoId");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AGD_Titulo");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("AGD_UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("AGD_UsuarioInclusao");

                    b.Property<int>("Visibilidade")
                        .HasColumnType("int")
                        .HasColumnName("AGD_Visibilidade");

                    b.HasKey("Id");

                    b.HasIndex("DataInicio");

                    b.HasIndex("OperadorId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("TipoId");

                    b.HasIndex("OperadorId", "DataInicio", "DataFim");

                    b.ToTable("tbagenda");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.AgendaParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendaId")
                        .HasColumnType("int")
                        .HasColumnName("AgendaId");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<string>("ParticipanteId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("ParticipanteId");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("AgendaId", "ParticipanteId")
                        .IsUnique();

                    b.ToTable("tbagendaparticipante");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.AuditoriaImplantacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AUD_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AUD_Acao");

                    b.Property<string>("AntesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUD_AntesJson");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("AUD_Data");

                    b.Property<string>("DepoisJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUD_DepoisJson");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AUD_Entidade");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int")
                        .HasColumnName("AUD_EntidadeId");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AUD_Observacao");

                    b.Property<string>("Usuario")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("AUD_Usuario");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("Usuario");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("tbauditoriaimplantacao");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ChamadoLegado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CHAMADO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("CLIENTE_ID");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_FECHAMENTO");

                    b.Property<DateTime?>("DataPrevisao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_PREVISAO");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.ToTable("tbchamado", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ClienteLegado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CLIENTE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Cnpj")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Fantasia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FANTASIA");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.HasKey("Id");

                    b.ToTable("tbcliente", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ColunaKanban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CLK_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit")
                        .HasColumnName("CLK_Ativa");

                    b.Property<string>("Cor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CLK_Cor");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLK_DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLK_DataInclusao");

                    b.Property<int?>("LimiteWip")
                        .HasColumnType("int")
                        .HasColumnName("CLK_LimiteWip");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLK_Nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("CLK_Ordem");

                    b.Property<bool>("Padrao")
                        .HasColumnType("bit")
                        .HasColumnName("CLK_Padrao");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLK_UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLK_UsuarioInclusao");

                    b.HasKey("Id");

                    b.ToTable("tbcolunakanban");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ComentarioTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CMT_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CMT_AutorId");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("CMT_DataInclusao");

                    b.Property<int>("TarefaId")
                        .HasColumnType("int")
                        .HasColumnName("CMT_TarefaId");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CMT_Texto");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("tbcomentariotarefa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.FuncionarioLegado", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FUNCIONARIO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionarioId"));

                    b.Property<string>("Ativo")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ATIVO");

                    b.Property<int?>("FuncaoId")
                        .HasColumnType("int")
                        .HasColumnName("FUNCAO_ID");

                    b.Property<string>("OperadorId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OPERADOR_ID");

                    b.HasKey("FuncionarioId");

                    b.ToTable("tbfuncionario", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRJ_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_ClienteId");

                    b.Property<int?>("ClienteLegadoId")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_ClienteLegadoId");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PRJ_Codigo");

                    b.Property<int?>("ColunaKanbanId")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_ColunaKanbanId");

                    b.Property<string>("CriadorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRJ_CriadorId");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataAlteracao");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataConclusao");

                    b.Property<DateTime?>("DataGoLivePrevista")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataGoLivePrevista");

                    b.Property<DateTime?>("DataGoLiveReal")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataGoLiveReal");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataInclusao");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataInicio");

                    b.Property<DateTime?>("DataPrevisao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataPrevisao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("PRJ_Descricao");

                    b.Property<int?>("HorasPlanejadas")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_HorasPlanejadas");

                    b.Property<int?>("HorasRealizadas")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_HorasRealizadas");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PRJ_Nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("PRJ_Observacao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_Prioridade");

                    b.Property<int>("Progresso")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_Progresso");

                    b.Property<string>("ResponsavelId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRJ_ResponsavelId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_Status");

                    b.Property<int>("TipoProjetoId")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_TipoProjetoId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRJ_UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRJ_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ColunaKanbanId");

                    b.HasIndex("TipoProjetoId");

                    b.ToTable("tbprojeto");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PEP_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtrasoDias")
                        .HasColumnType("int")
                        .HasColumnName("PEP_AtrasoDias");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PEP_DataAlteracao");

                    b.Property<DateTime?>("DataFimPrevista")
                        .HasColumnType("datetime2")
                        .HasColumnName("PEP_DataFimPrevista");

                    b.Property<DateTime?>("DataFimReal")
                        .HasColumnType("datetime2")
                        .HasColumnName("PEP_DataFimReal");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PEP_DataInclusao");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("PEP_DataInicio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PEP_Estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PEP_Nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("PEP_Ordem");

                    b.Property<int>("Percentual")
                        .HasColumnType("int")
                        .HasColumnName("PEP_Percentual");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int")
                        .HasColumnName("PEP_ProjetoId");

                    b.Property<string>("ResponsavelId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PEP_ResponsavelId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PEP_UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PEP_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId", "Ordem")
                        .IsUnique();

                    b.ToTable("tbprojetoetapa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapaChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PEC_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluido")
                        .HasColumnType("bit")
                        .HasColumnName("PEC_Concluido");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PEC_DataAlteracao");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PEC_DataConclusao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PEC_DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PEC_Descricao");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("PEC_Ordem");

                    b.Property<int>("ProjetoEtapaId")
                        .HasColumnType("int")
                        .HasColumnName("PEC_ProjetoEtapaId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PEC_UsuarioAlteracao");

                    b.Property<string>("UsuarioConclusao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PEC_UsuarioConclusao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PEC_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoEtapaId");

                    b.ToTable("tbprojetoetapachecklist");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapaComentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PEC_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("PEC_Data");

                    b.Property<int>("ProjetoEtapaId")
                        .HasColumnType("int")
                        .HasColumnName("PEC_ProjetoEtapaId");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("PEC_Texto");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PEC_Usuario");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoEtapaId");

                    b.ToTable("tbprojetoetapacomentario");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapaDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PED_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PED_DataInclusao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PED_Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PED_Nome");

                    b.Property<int>("ProjetoEtapaId")
                        .HasColumnType("int")
                        .HasColumnName("PED_ProjetoEtapaId");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PED_Url");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PED_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoEtapaId");

                    b.ToTable("tbprojetoetapadocumento");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapaHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PEH_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("PEH_Acao");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("PEH_Data");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("PEH_Detalhes");

                    b.Property<int>("ProjetoEtapaId")
                        .HasColumnType("int")
                        .HasColumnName("PEH_ProjetoEtapaId");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PEH_Usuario");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoEtapaId");

                    b.ToTable("tbprojetoetahistorico");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRF_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Arquivada")
                        .HasColumnType("bit")
                        .HasColumnName("TRF_Arquivada");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("bit")
                        .HasColumnName("TRF_Bloqueada");

                    b.Property<int?>("ChamadoLegadoId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_ChamadoLegadoId");

                    b.Property<int?>("ColunaKanbanId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_ColunaKanbanId");

                    b.Property<string>("CriadorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRF_CriadorId");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataAlteracao");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataConclusao");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataEntrega");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataInclusao");

                    b.Property<DateTime?>("DataPrevisao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataPrevisao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("TRF_Descricao");

                    b.Property<int?>("HorasEstimadas")
                        .HasColumnType("int")
                        .HasColumnName("TRF_HorasEstimadas");

                    b.Property<int?>("HorasRealizadas")
                        .HasColumnType("int")
                        .HasColumnName("TRF_HorasRealizadas");

                    b.Property<string>("MotivoBloqueio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TRF_MotivoBloqueio");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("TRF_Ordem");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("TRF_Prioridade");

                    b.Property<int?>("ProjetoEtapaId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_ProjetoEtapaId");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_ProjetoId");

                    b.Property<string>("ResponsavelId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRF_ResponsavelId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("TRF_Status");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TRF_TipoTarefa");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TRF_Titulo");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRF_UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRF_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("ColunaKanbanId");

                    b.HasIndex("ProjetoEtapaId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("tbtarefa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.TarefaApontamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("APT_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("APT_Data");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("APT_DataInclusao");

                    b.Property<decimal>("Horas")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("APT_Horas");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("APT_Observacao");

                    b.Property<string>("OperadorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OPERADOR_ID");

                    b.Property<int>("TarefaId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_Id");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("APT_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId", "Data");

                    b.ToTable("tbtarefaapontamento");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.TarefaChamado", b =>
                {
                    b.Property<int>("TarefaId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_Id");

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int")
                        .HasColumnName("CHAMADO_ID");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataInclusao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRF_UsuarioInclusao");

                    b.HasKey("TarefaId", "ChamadoId");

                    b.HasIndex("ChamadoId");

                    b.ToTable("tbtarefachamado");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.TarefaResponsavel", b =>
                {
                    b.Property<int>("TarefaId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_Id");

                    b.Property<string>("OperadorId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OPERADOR_ID");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataInclusao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRF_UsuarioInclusao");

                    b.HasKey("TarefaId", "OperadorId");

                    b.HasIndex("OperadorId");

                    b.ToTable("tbtarefareponsavel");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.TipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("Cor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("Cor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("tbtipoevento");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.TipoProjeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TPP_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("TPP_Ativo");

                    b.Property<bool>("ClienteObrigatorio")
                        .HasColumnType("bit")
                        .HasColumnName("TPP_ClienteObrigatorio");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TPP_Codigo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TPP_DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TPP_DataInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TPP_Nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("TPP_Ordem");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TPP_UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TPP_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("tbtipoprojeto");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Operador", b =>
                {
                    b.Property<string>("OperadorId")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("OPERADOR_ID");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<DateTime?>("DataUltimoAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ULTIMO_ACESSO");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("FuncaoId")
                        .HasColumnType("int")
                        .HasColumnName("FUNCAO_ID");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("PerfilId")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("PERFIL_ID");

                    b.Property<string>("PerfilSkin")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PERFIL_SKIN");

                    b.Property<bool?>("SeAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("SE_ADMIN");

                    b.Property<string>("SeAtivo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("SE_ATIVO");

                    b.Property<string>("Senha")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SENHA");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("USUARIO_ALTERACAO");

                    b.Property<string>("UsuarioInclusao")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("USUARIO_INCLUSAO");

                    b.HasKey("OperadorId");

                    b.HasIndex("FuncaoId");

                    b.ToTable("tboperador");
                });

            modelBuilder.Entity("Central_BackEnd.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiraEm");

                    b.Property<string>("OperadorId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("OperadorId");

                    b.Property<bool>("Revogado")
                        .HasColumnType("bit")
                        .HasColumnName("Revogado");

                    b.Property<string>("SubstituidoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubstituidoPor");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TokenHash");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.HasIndex("TokenHash");

                    b.ToTable("tbrefreshtoken");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.AgendaItem", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Central_BackEnd.Models.Implantacao.TipoEvento", "TipoEvento")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Projeto");

                    b.Navigation("TipoEvento");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.AgendaParticipante", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.AgendaItem", "Agenda")
                        .WithMany("Participantes")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Central_BackEnd.Models.Operador", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agenda");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ComentarioTarefa", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Tarefa", "Tarefa")
                        .WithMany()
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Projeto", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.ClienteLegado", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Central_BackEnd.Models.Implantacao.ColunaKanban", "ColunaKanban")
                        .WithMany()
                        .HasForeignKey("ColunaKanbanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Central_BackEnd.Models.Implantacao.TipoProjeto", "TipoProjeto")
                        .WithMany()
                        .HasForeignKey("TipoProjetoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ColunaKanban");

                    b.Navigation("TipoProjeto");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapa", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Projeto", "Projeto")
                        .WithMany("Etapas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapaChecklist", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.ProjetoEtapa", "ProjetoEtapa")
                        .WithMany("Checklist")
                        .HasForeignKey("ProjetoEtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjetoEtapa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapaComentario", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.ProjetoEtapa", "ProjetoEtapa")
                        .WithMany("Comentarios")
                        .HasForeignKey("ProjetoEtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjetoEtapa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapaDocumento", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.ProjetoEtapa", "ProjetoEtapa")
                        .WithMany("Documentos")
                        .HasForeignKey("ProjetoEtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjetoEtapa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapaHistorico", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.ProjetoEtapa", "ProjetoEtapa")
                        .WithMany("Historico")
                        .HasForeignKey("ProjetoEtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjetoEtapa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Tarefa", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.ColunaKanban", "ColunaKanban")
                        .WithMany()
                        .HasForeignKey("ColunaKanbanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Central_BackEnd.Models.Implantacao.ProjetoEtapa", "ProjetoEtapa")
                        .WithMany()
                        .HasForeignKey("ProjetoEtapaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Central_BackEnd.Models.Implantacao.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ColunaKanban");

                    b.Navigation("Projeto");

                    b.Navigation("ProjetoEtapa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.TarefaApontamento", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Tarefa", "Tarefa")
                        .WithMany("Apontamentos")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.TarefaChamado", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Tarefa", "Tarefa")
                        .WithMany("Chamados")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.TarefaResponsavel", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Tarefa", "Tarefa")
                        .WithMany("Responsaveis")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Operador", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("Central_BackEnd.Models.RefreshToken", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Operador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.AgendaItem", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Projeto", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ProjetoEtapa", b =>
                {
                    b.Navigation("Checklist");

                    b.Navigation("Comentarios");

                    b.Navigation("Documentos");

                    b.Navigation("Historico");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Tarefa", b =>
                {
                    b.Navigation("Apontamentos");

                    b.Navigation("Chamados");

                    b.Navigation("Responsaveis");
                });
#pragma warning restore 612, 618
        }
    }
}
