// <auto-generated />
using System;
using Central_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Central_BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Central_BackEnd.Models.Acessos.AuditoriaAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAcesso");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Empresa");

                    b.Property<string>("EnderecoIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EnderecoIP");

                    b.Property<TimeSpan>("HoraAcesso")
                        .HasColumnType("time")
                        .HasColumnName("HoraAcesso");

                    b.Property<string>("Navegador")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Navegador");

                    b.Property<string>("TipoInformacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TipoInformacao");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Usuario");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaAcessos");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Funcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FUNCAO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Classificacao")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CLASSIFICACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("CC_Funcao");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.AgendaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AGD_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AGD_Cor");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("AGD_DataAlteracao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("AGD_DataFim");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("AGD_DataInclusao");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("AGD_DataInicio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("AGD_Descricao");

                    b.Property<bool>("DiaInteiro")
                        .HasColumnType("bit")
                        .HasColumnName("AGD_DiaInteiro");

                    b.Property<string>("Local")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AGD_Local");

                    b.Property<string>("OperadorId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("AGD_OperadorId");

                    b.Property<int>("PadraoRecorrencia")
                        .HasColumnType("int")
                        .HasColumnName("AGD_PadraoRecorrencia");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("int")
                        .HasColumnName("AGD_ProjetoId");

                    b.Property<bool>("Recorrente")
                        .HasColumnType("bit")
                        .HasColumnName("AGD_Recorrente");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("AGD_Tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AGD_Titulo");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("AGD_UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("AGD_UsuarioInclusao");

                    b.Property<int>("Visibilidade")
                        .HasColumnType("int")
                        .HasColumnName("AGD_Visibilidade");

                    b.HasKey("Id");

                    b.HasIndex("DataInicio");

                    b.HasIndex("OperadorId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("IMPL_Agenda");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.AuditoriaImplantacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AUD_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AUD_Acao");

                    b.Property<string>("AntesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUD_AntesJson");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("AUD_Data");

                    b.Property<string>("DepoisJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUD_DepoisJson");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AUD_Entidade");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int")
                        .HasColumnName("AUD_EntidadeId");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AUD_Observacao");

                    b.Property<string>("Usuario")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("AUD_Usuario");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("Usuario");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("IMPL_Auditoria");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CLI_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("CLI_Ativo");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CLI_Cnpj");

                    b.Property<string>("Contato")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CLI_Contato");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLI_DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLI_DataInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CLI_Nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("CLI_Observacao");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLI_UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLI_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("IMPL_Cliente");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ColunaKanban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CLK_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit")
                        .HasColumnName("CLK_Ativa");

                    b.Property<string>("Cor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CLK_Cor");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLK_DataInclusao");

                    b.Property<int?>("LimiteWip")
                        .HasColumnType("int")
                        .HasColumnName("CLK_LimiteWip");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLK_Nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("CLK_Ordem");

                    b.Property<bool>("Padrao")
                        .HasColumnType("bit")
                        .HasColumnName("CLK_Padrao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLK_UsuarioInclusao");

                    b.HasKey("Id");

                    b.ToTable("IMPL_ColunaKanban");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ComentarioTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CMT_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CMT_AutorId");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("CMT_DataInclusao");

                    b.Property<int>("TarefaId")
                        .HasColumnType("int")
                        .HasColumnName("CMT_TarefaId");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("CMT_Texto");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("IMPL_ComentarioTarefa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EQP_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit")
                        .HasColumnName("EQP_Ativa");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("EQP_DataInclusao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("EQP_Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EQP_Nome");

                    b.Property<string>("PrefixoCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EQP_PrefixoCodigo");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EQP_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("IMPL_Equipe");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ETP_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit")
                        .HasColumnName("ETP_Ativa");

                    b.Property<bool>("Concluida")
                        .HasColumnType("bit")
                        .HasColumnName("ETP_Concluida");

                    b.Property<string>("Cor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ETP_Cor");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ETP_DataInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ETP_Nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("ETP_Ordem");

                    b.Property<int?>("TipoProjetoId")
                        .HasColumnType("int")
                        .HasColumnName("ETP_TipoProjetoId");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ETP_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("TipoProjetoId");

                    b.ToTable("IMPL_Etapa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.MembroEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MBE_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("MBE_DataInclusao");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int")
                        .HasColumnName("MBE_EquipeId");

                    b.Property<string>("OperadorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MBE_OperadorId");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId", "OperadorId")
                        .IsUnique();

                    b.ToTable("IMPL_MembroEquipe");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRJ_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_ClienteId");

                    b.Property<int?>("ClienteLegadoId")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_ClienteLegadoId");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PRJ_Codigo");

                    b.Property<int?>("ColunaKanbanId")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_ColunaKanbanId");

                    b.Property<string>("CriadorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRJ_CriadorId");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataAlteracao");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataConclusao");

                    b.Property<DateTime?>("DataGoLivePrevista")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataGoLivePrevista");

                    b.Property<DateTime?>("DataGoLiveReal")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataGoLiveReal");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataInclusao");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataInicio");

                    b.Property<DateTime?>("DataPrevisao")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRJ_DataPrevisao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("PRJ_Descricao");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_EquipeId");

                    b.Property<int?>("HorasPlanejadas")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_HorasPlanejadas");

                    b.Property<int?>("HorasRealizadas")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_HorasRealizadas");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PRJ_Nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("PRJ_Observacao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_Prioridade");

                    b.Property<int>("Progresso")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_Progresso");

                    b.Property<string>("ResponsavelId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRJ_ResponsavelId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_Status");

                    b.Property<int>("TipoProjetoId")
                        .HasColumnType("int")
                        .HasColumnName("PRJ_TipoProjetoId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRJ_UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRJ_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ColunaKanbanId");

                    b.HasIndex("EquipeId");

                    b.HasIndex("TipoProjetoId");

                    b.ToTable("IMPL_Projeto");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRF_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("bit")
                        .HasColumnName("TRF_Bloqueada");

                    b.Property<int?>("ChamadoLegadoId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_ChamadoLegadoId");

                    b.Property<int?>("ColunaKanbanId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_ColunaKanbanId");

                    b.Property<string>("CriadorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRF_CriadorId");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataAlteracao");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataConclusao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataInclusao");

                    b.Property<DateTime?>("DataPrevisao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TRF_DataPrevisao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("TRF_Descricao");

                    b.Property<int?>("EtapaId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_EtapaId");

                    b.Property<int?>("HorasEstimadas")
                        .HasColumnType("int")
                        .HasColumnName("TRF_HorasEstimadas");

                    b.Property<int?>("HorasRealizadas")
                        .HasColumnType("int")
                        .HasColumnName("TRF_HorasRealizadas");

                    b.Property<string>("MotivoBloqueio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TRF_MotivoBloqueio");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("TRF_Ordem");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("TRF_Prioridade");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int")
                        .HasColumnName("TRF_ProjetoId");

                    b.Property<string>("ResponsavelId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRF_ResponsavelId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("TRF_Status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TRF_Titulo");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRF_UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRF_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("ColunaKanbanId");

                    b.HasIndex("EtapaId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("IMPL_Tarefa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.TipoProjeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TPP_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("TPP_Ativo");

                    b.Property<bool>("ClienteObrigatorio")
                        .HasColumnType("bit")
                        .HasColumnName("TPP_ClienteObrigatorio");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TPP_Codigo");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("TPP_DataInclusao");

                    b.Property<int?>("EquipeId")
                        .HasColumnType("int")
                        .HasColumnName("TPP_EquipeId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TPP_Nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("TPP_Ordem");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TPP_UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EquipeId");

                    b.ToTable("IMPL_TipoProjeto");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Operador", b =>
                {
                    b.Property<string>("OperadorId")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("OPERADOR_ID");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<DateTime?>("DataUltimoAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ULTIMO_ACESSO");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("FuncaoId")
                        .HasColumnType("int")
                        .HasColumnName("FUNCAO_ID");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("PerfilId")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("PERFIL_ID");

                    b.Property<string>("PerfilSkin")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PERFIL_SKIN");

                    b.Property<bool?>("SeAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("SE_ADMIN");

                    b.Property<string>("SeAtivo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("SE_ATIVO");

                    b.Property<string>("Senha")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SENHA");

                    b.Property<string>("UsuarioAlteracao")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("USUARIO_ALTERACAO");

                    b.Property<string>("UsuarioInclusao")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("USUARIO_INCLUSAO");

                    b.HasKey("OperadorId");

                    b.HasIndex("FuncaoId");

                    b.ToTable("TBOPERADOR");
                });

            modelBuilder.Entity("Central_BackEnd.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiraEm");

                    b.Property<string>("OperadorId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("OperadorId");

                    b.Property<bool>("Revogado")
                        .HasColumnType("bit")
                        .HasColumnName("Revogado");

                    b.Property<string>("SubstituidoPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubstituidoPor");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TokenHash");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.HasIndex("TokenHash");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.AgendaItem", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.ComentarioTarefa", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Tarefa", "Tarefa")
                        .WithMany()
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Etapa", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.TipoProjeto", "TipoProjeto")
                        .WithMany()
                        .HasForeignKey("TipoProjetoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TipoProjeto");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.MembroEquipe", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Projeto", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Central_BackEnd.Models.Implantacao.ColunaKanban", "ColunaKanban")
                        .WithMany()
                        .HasForeignKey("ColunaKanbanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Central_BackEnd.Models.Implantacao.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Central_BackEnd.Models.Implantacao.TipoProjeto", "TipoProjeto")
                        .WithMany()
                        .HasForeignKey("TipoProjetoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ColunaKanban");

                    b.Navigation("Equipe");

                    b.Navigation("TipoProjeto");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.Tarefa", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.ColunaKanban", "ColunaKanban")
                        .WithMany()
                        .HasForeignKey("ColunaKanbanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Central_BackEnd.Models.Implantacao.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Central_BackEnd.Models.Implantacao.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColunaKanban");

                    b.Navigation("Etapa");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Implantacao.TipoProjeto", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Implantacao.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("Central_BackEnd.Models.Operador", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("Central_BackEnd.Models.RefreshToken", b =>
                {
                    b.HasOne("Central_BackEnd.Models.Operador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operador");
                });
#pragma warning restore 612, 618
        }
    }
}
