namespace Central_BackEnd.Dtos.Implantacao;

public record ProjetoResumo(
    int Id,
    string Codigo,
    string Nome,
    string EquipeNome,
    string TipoProjetoNome,
    int? ClienteId,
    string? ClienteNome,
    int? ClienteLegadoId,
    string? ClienteLegadoNome,
    string Status,
    int Prioridade,
    int Progresso,
    string? ResponsavelId,
    string? ResponsavelNome,
    DateTime? DataPrevisao,
    DateTime? DataConclusao,
    DateTime DataInclusao);

public record ProjetoDetalhe(
    int Id,
    string Codigo,
    string Nome,
    string? Descricao,
    int EquipeId,
    string EquipeNome,
    int TipoProjetoId,
    string TipoProjetoNome,
    int? ClienteId,
    string? ClienteNome,
    int? ClienteLegadoId,
    string? ClienteLegadoNome,
    string? ClienteLegadoCnpj,
    string? ResponsavelId,
    string? ResponsavelNome,
    string CriadorId,
    string CriadorNome,
    string Status,
    int? ColunaKanbanId,
    string? ColunaKanbanNome,
    int Prioridade,
    int Progresso,
    DateTime? DataInicio,
    DateTime? DataPrevisao,
    DateTime? DataConclusao,
    DateTime? DataGoLivePrevista,
    DateTime? DataGoLiveReal,
    int? HorasPlanejadas,
    int? HorasRealizadas,
    string? Observacao,
    int TotalTarefas,
    int TarefasConcluidas,
    int TarefasAtrasadas,
    DateTime DataInclusao,
    string UsuarioInclusao,
    DateTime? DataAlteracao,
    string? UsuarioAlteracao);

public record ProjetoCriarRequest(
    string Nome,
    string? Descricao,
    int EquipeId,
    int TipoProjetoId,
    int? ClienteId,
    int? ClienteLegadoId,
    string? ResponsavelId,
    string CriadorId,
    int? ColunaKanbanId,
    int Prioridade,
    DateTime? DataInicio,
    DateTime? DataPrevisao,
    DateTime? DataGoLivePrevista,
    int? HorasPlanejadas,
    string? Observacao);

public record ProjetoAtualizarRequest(
    string Nome,
    string? Descricao,
    int EquipeId,
    int TipoProjetoId,
    int? ClienteId,
    int? ClienteLegadoId,
    string? ResponsavelId,
    int? ColunaKanbanId,
    int Prioridade,
    int Progresso,
    DateTime? DataInicio,
    DateTime? DataPrevisao,
    DateTime? DataConclusao,
    DateTime? DataGoLivePrevista,
    DateTime? DataGoLiveReal,
    int? HorasPlanejadas,
    int? HorasRealizadas,
    string? Observacao,
    string UsuarioAlteracao);

public record ProjetoMudarStatusRequest(
    string Status,
    int? ColunaKanbanId,
    string UsuarioAlteracao);

public record ProjetoFiltro(
    string? Equipe,
    string? Tipo,
    string? Status,
    int? ClienteId,
    string? ResponsavelId,
    string? Buscar);
