import { buscarSingleTerm } from '@shared/utils/texto.helper';

export type NivelCurso = 'Iniciante' | 'Intermediário' | 'Avançado';

export type PlataformaCurso = 'Alura' | 'YouTube' | 'Microsoft Learn' | 'Documentação' | 'Curso em Vídeo' | 'Cisco' | 'Fundação Bradesco' | 'Postman Academy';

export interface Curso {
  id: string;
  titulo: string;
  descricao: string;
  categoria: string;
  plataforma: PlataformaCurso;
  autor: string;
  canal: string;
  duracao: string;
  nivel: NivelCurso;
  idioma: 'PT-BR' | 'EN';
  url: string;
  playlistId?: string;
  videoId?: string;
  embeddable: boolean;
  tags: string[];
  professor?: string;
  preRequisitos?: string[];
  objetivos?: string[];
  tecnologiasRelacionadas?: string[];
  trilhas?: string[];
  emDestaque?: boolean;
}

export interface Trilha {
  id: string;
  nome: string;
  descricao: string;
  icone: string;
  cor: string;
  cursoIds: string[];
}

export const categoriasCursos = [
  { id: 'alura', nome: 'Alura', icone: 'bi-mortarboard-fill', cor: '#0f4c81', descricao: 'Plataforma oficial de capacitação da JCA Soluções.' },
  { id: 'frontend', nome: 'Front-end', icone: 'bi-window-stack', cor: '#2563eb', descricao: 'Angular, HTML, CSS, JavaScript, TypeScript e Bootstrap.' },
  { id: 'backend', nome: 'Back-end', icone: 'bi-server', cor: '#16a34a', descricao: '.NET, C#, ASP.NET Core e REST APIs.' },
  { id: 'banco', nome: 'Banco de Dados', icone: 'bi-database-fill', cor: '#f59e0b', descricao: 'SQL Server e JSON.' },
  { id: 'versionamento', nome: 'Versionamento', icone: 'bi-git', cor: '#ea580c', descricao: 'Git e GitHub.' },
  { id: 'infra', nome: 'Infraestrutura', icone: 'bi-hdd-network-fill', cor: '#dc2626', descricao: 'Docker, Windows Server, IIS, Redes e TCP/IP.' },
  { id: 'ferramentas', nome: 'Ferramentas', icone: 'bi-tools', cor: '#0891b2', descricao: 'Postman e utilitários para APIs.' },
  { id: 'arquitetura', nome: 'Arquitetura', icone: 'bi-diagram-3-fill', cor: '#7c3aed', descricao: 'Clean Architecture, SOLID, Design Patterns e DevOps.' },
  { id: 'delphi', nome: 'Delphi', icone: 'bi-code-square', cor: '#E44D26', descricao: 'Linguagem Delphi e/Object Pascal.' },
  { id: 'curso-em-video', nome: 'Curso em Vídeo', icone: 'bi-play-btn-fill', cor: '#FF8C00', descricao: 'Cursos gratuitos de Gustavo Guanabara (Python, MySQL, Algoritmos, Git, Redes, Linux).' },
  { id: 'microsoft-learn', nome: 'Microsoft Learn', icone: 'bi-microsoft', cor: '#0078D4', descricao: 'Trilhas e módulos gratuitos da Microsoft (SQL Server, Azure, PowerShell, Docker).' },
  { id: 'cisco', nome: 'Cisco', icone: 'bi-ethernet', cor: '#049FD9', descricao: 'Cursos gratuitos de redes, cibersegurança e Python (Skills for All).' },
  { id: 'fundacao-bradesco', nome: 'Fundação Bradesco', icone: 'bi-mortarboard', cor: '#CC092F', descricao: 'Escola Virtual: Excel, LGPD, Segurança da Informação e mais.' },
  { id: 'postman-academy', nome: 'Postman Academy', icone: 'bi-postage-fill', cor: '#FF6C37', descricao: 'Aprenda APIs, testes e automação de forma interativa.' },
  { id: 'atendimento', nome: 'Atendimento', icone: 'bi-headset', cor: '#0891b2', descricao: 'Atendimento ao cliente, comunicação interpessoal e relacionamento.' }
];

export const trilhas: Trilha[] = [
  {
    id: 'fundamentos',
    nome: 'Fundamentos da Programação',
    descricao: 'Lógica, algoritmos, Python, HTML, CSS e JavaScript do zero.',
    icone: 'bi-braces',
    cor: '#14B8A6',
    cursoIds: ['cev-algoritmos', 'cev-python3', 'alura-html', 'alura-css', 'alura-javascript', 'yt-curso-em-video-html5', 'yt-curso-em-video-css3', 'yt-curso-em-video-javascript', 'yt-origamid-html', 'yt-origamid-css', 'cisco-python']
  },
  {
    id: 'redes',
    nome: 'Redes de Computadores',
    descricao: 'Conceitos de redes, TCP/IP, DNS, DHCP e segurança de redes.',
    icone: 'bi-diagram-2-fill',
    cor: '#06B6D4',
    cursoIds: ['yt-boson-redes', 'yt-professor-ramos-redes', 'yt-boson-tcpip', 'yt-professor-ramos-tcpip', 'cisco-redes']
  },
  {
    id: 'banco-de-dados',
    nome: 'Banco de Dados',
    descricao: 'SQL Server, MySQL, modelagem, consultas e JSON.',
    icone: 'bi-database-fill',
    cor: '#F59E0B',
    cursoIds: ['alura-sql-server', 'cev-mysql', 'mslearn-sql-server', 'yt-macoratti-sql-server', 'yt-boson-sql-server', 'yt-microsoft-reactor-sql-server', 'yt-codigo-fonte-json', 'yt-balta-json']
  },
  {
    id: 'infraestrutura',
    nome: 'Infraestrutura',
    descricao: 'Windows Server, IIS, Docker e serviços de servidor.',
    icone: 'bi-hdd-network-fill',
    cor: '#DC2626',
    cursoIds: ['alura-windows-server', 'alura-docker', 'mslearn-windows-server', 'mslearn-iis', 'mslearn-docker', 'yt-boson-windows-server', 'yt-professor-ramos-windows-server', 'yt-boson-iis', 'yt-microsoft-reactor-iis', 'yt-linuxtips-docker', 'yt-full-cycle-docker', 'yt-codigo-fonte-docker']
  },
  {
    id: 'apis-integracoes',
    nome: 'APIs e Integrações',
    descricao: 'REST, autenticação JWT, testes e consumo de APIs.',
    icone: 'bi-plug-fill',
    cor: '#8B5CF6',
    cursoIds: ['alura-rest-api', 'alura-jwt', 'mslearn-aspnet-webapi', 'postman-academy-apis', 'yt-desenvolvedor-io-rest-api', 'yt-balta-rest-api', 'yt-codigo-fonte-rest-api', 'yt-codigo-fonte-postman', 'yt-desenvolvedor-io-postman']
  },
  {
    id: 'seguranca',
    nome: 'Segurança da Informação',
    descricao: 'Cibersegurança, LGPD, JWT e boas práticas de proteção.',
    icone: 'bi-shield-lock-fill',
    cor: '#10B981',
    cursoIds: ['alura-jwt', 'mslearn-seguranca', 'cisco-ciberseguranca', 'bradesco-lgpd', 'bradesco-seguranca-info']
  },
  {
    id: 'sistemas-operacionais',
    nome: 'Sistemas Operacionais',
    descricao: 'Linux, PowerShell, Windows e administração de sistemas.',
    icone: 'bi-terminal-fill',
    cor: '#2563EB',
    cursoIds: ['cev-linux', 'mslearn-powershell', 'mslearn-windows-server', 'yt-boson-windows-server']
  },
  {
    id: 'ferramentas',
    nome: 'Ferramentas',
    descricao: 'Git, GitHub, Postman e produtividade do dia a dia.',
    icone: 'bi-tools',
    cor: '#EA580C',
    cursoIds: ['alura-git', 'alura-github', 'bradesco-excel', 'yt-curso-em-video-git', 'yt-codigo-fonte-git', 'yt-filipe-deschamps-git', 'yt-codigo-fonte-postman', 'yt-desenvolvedor-io-postman']
  },
  {
    id: 'desenvolvimento',
    nome: 'Desenvolvimento de Software',
    descricao: 'Angular, TypeScript, C#, ASP.NET Core, arquitetura e boas práticas.',
    icone: 'bi-code-slash',
    cor: '#7C3AED',
    cursoIds: ['alura-angular', 'alura-typescript', 'alura-bootstrap', 'alura-csharp', 'alura-aspnet-core', 'alura-arquitetura', 'alura-solid', 'alura-design-patterns', 'alura-clean-architecture', 'alura-devops', 'yt-loiane-angular', 'yt-cod3r-angular', 'yt-fernanda-kipper-angular', 'yt-hora-de-codar-angular', 'yt-loiane-typescript', 'yt-codigo-fonte-typescript', 'yt-balta-csharp', 'yt-macoratti-csharp', 'yt-desenvolvedor-io-csharp', 'yt-balta-aspnet-core', 'yt-desenvolvedor-io-aspnet-core', 'yt-microsoft-reactor-aspnet-core', 'yt-full-cycle-clean-architecture', 'yt-desenvolvedor-io-arquitetura', 'yt-balta-solid', 'yt-full-cycle-solid', 'yt-balta-design-patterns', 'yt-macoratti-design-patterns', 'yt-linuxtips-devops', 'yt-full-cycle-devops']
  }
];

// ══════════════════════════════════════════════════════════
// ALURA — Formações corporativas
// ══════════════════════════════════════════════════════════

export const cursosAlura: Curso[] = [
  {
    id: 'alura-angular',
    titulo: 'Angular',
    descricao: 'Formação completa em Angular: componentes, rotas, formulários, HTTP, RxJS e boas práticas.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '40h+',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-angular',
    embeddable: false,
    tags: ['angular', 'frontend', 'typescript', 'spa'],
    professor: 'Various',
    preRequisitos: ['HTML', 'CSS', 'JavaScript básico'],
    objetivos: ['Criar aplicações SPA com Angular', 'Utilizar componentes e módulos', 'Trabalhar com rotas e formulários', 'Consumir APIs REST'],
    tecnologiasRelacionadas: ['TypeScript', 'RxJS', 'HTML', 'CSS'],
    trilhas: ['desenvolvedor'],
    emDestaque: true
  },
  {
    id: 'alura-typescript',
    titulo: 'TypeScript',
    descricao: 'Formação em TypeScript: tipos, interfaces, generics, classes e boas práticas de tipagem.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '20h+',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-typescript',
    embeddable: false,
    tags: ['typescript', 'frontend', 'backend', 'tipos'],
    professor: 'Various',
    preRequisitos: ['JavaScript básico'],
    objetivos: ['Tipar código com TypeScript', 'Utilizar interfaces e generics', 'Melhorar manutenibilidade do código'],
    tecnologiasRelacionadas: ['JavaScript', 'Angular', 'Node.js'],
    trilhas: ['desenvolvedor'],
    emDestaque: true
  },
  {
    id: 'alura-html',
    titulo: 'HTML',
    descricao: 'Formação em HTML5: estrutura, semântica, formulários, acessibilidade e boas práticas.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '15h+',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-html-e-css',
    embeddable: false,
    tags: ['html', 'frontend', 'web', 'semantica'],
    professor: 'Various',
    preRequisitos: [],
    objetivos: ['Estruturar páginas web com HTML5', 'Utilizar semântica corretamente', 'Criar formulários acessíveis'],
    tecnologiasRelacionadas: ['CSS', 'JavaScript'],
    trilhas: ['novo-colaborador'],
    emDestaque: true
  },
  {
    id: 'alura-css',
    titulo: 'CSS',
    descricao: 'Formação em CSS3: seletores, flexbox, grid, responsividade e pré-processadores.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '20h+',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-html-e-css',
    embeddable: false,
    tags: ['css', 'frontend', 'web', 'flexbox', 'grid'],
    professor: 'Various',
    preRequisitos: ['HTML básico'],
    objetivos: ['Estilizar páginas com CSS3', 'Utilizar flexbox e grid', 'Criar layouts responsivos'],
    tecnologiasRelacionadas: ['HTML', 'Bootstrap'],
    trilhas: ['novo-colaborador'],
    emDestaque: true
  },
  {
    id: 'alura-bootstrap',
    titulo: 'Bootstrap',
    descricao: 'Formação em Bootstrap: grid, componentes, utilitários e customização do framework.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '10h+',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-bootstrap',
    embeddable: false,
    tags: ['bootstrap', 'frontend', 'css', 'ui'],
    professor: 'Various',
    preRequisitos: ['HTML', 'CSS básico'],
    objetivos: ['Criar layouts com Bootstrap', 'Utilizar componentes prontos', 'Customizar o framework'],
    tecnologiasRelacionadas: ['HTML', 'CSS', 'JavaScript'],
    trilhas: [],
    emDestaque: true
  },
  {
    id: 'alura-javascript',
    titulo: 'JavaScript',
    descricao: 'Formação completa em JavaScript: fundamentos, ES6+, DOM, assíncrono e boas práticas.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '30h+',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-javascript',
    embeddable: false,
    tags: ['javascript', 'frontend', 'web', 'es6'],
    professor: 'Various',
    preRequisitos: ['HTML', 'CSS básico'],
    objetivos: ['Programar com JavaScript moderno', 'Manipular o DOM', 'Trabalhar com assíncrono'],
    tecnologiasRelacionadas: ['HTML', 'CSS', 'TypeScript'],
    trilhas: ['novo-colaborador'],
    emDestaque: true
  },
  {
    id: 'alura-csharp',
    titulo: 'C#',
    descricao: 'Formação em C#: fundamentos, POO, LINQ, async/await e recursos modernos da linguagem.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '25h+',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-csharp',
    embeddable: false,
    tags: ['c#', 'backend', 'oop', 'dotnet'],
    professor: 'Various',
    preRequisitos: ['Lógica de programação'],
    objetivos: ['Desenvolver com C#', 'Utilizar POO', 'Trabalhar com LINQ e assíncrono'],
    tecnologiasRelacionadas: ['.NET', 'ASP.NET Core', 'SQL Server'],
    trilhas: ['desenvolvedor'],
    emDestaque: true
  },
  {
    id: 'alura-aspnet-core',
    titulo: 'ASP.NET Core',
    descricao: 'Formação em ASP.NET Core: Web API, Entity Framework Core, Identity e boas práticas.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '30h+',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-aspnet-core',
    embeddable: false,
    tags: ['aspnet', 'backend', 'api', 'dotnet'],
    professor: 'Various',
    preRequisitos: ['C#', 'POO'],
    objetivos: ['Criar Web APIs com ASP.NET Core', 'Utilizar Entity Framework Core', 'Implementar autenticação e autorização'],
    tecnologiasRelacionadas: ['C#', 'Entity Framework', 'SQL Server', 'REST API'],
    trilhas: ['desenvolvedor', 'analista-n2'],
    emDestaque: true
  },
  {
    id: 'alura-sql-server',
    titulo: 'SQL Server',
    descricao: 'Formação em SQL Server: consultas, joins, procedures, functions e administração.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '20h+',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-sql-server',
    embeddable: false,
    tags: ['sql server', 'banco', 'tsql', 'database'],
    professor: 'Various',
    preRequisitos: [],
    objetivos: ['Consultar dados com SQL', 'Criar procedures e functions', 'Gerenciar banco de dados'],
    tecnologiasRelacionadas: ['C#', 'ASP.NET Core', '.NET'],
    trilhas: ['analista-n1', 'analista-n2', 'desenvolvedor'],
    emDestaque: true
  },
  {
    id: 'alura-git',
    titulo: 'Git',
    descricao: 'Formação em Git: versionamento, branches, merges, rebase e boas práticas.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '8h+',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-git-e-github',
    embeddable: false,
    tags: ['git', 'versionamento', 'controle-versao'],
    professor: 'Various',
    preRequisitos: [],
    objetivos: ['Versionar código com Git', 'Trabalhar com branches', 'Resolver conflitos de merge'],
    tecnologiasRelacionadas: ['GitHub'],
    trilhas: ['novo-colaborador'],
    emDestaque: true
  },
  {
    id: 'alura-github',
    titulo: 'GitHub',
    descricao: 'Formação em GitHub: repositórios, pull requests, issues, actions e colaboração.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '10h+',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-git-e-github',
    embeddable: false,
    tags: ['github', 'versionamento', 'colaboracao'],
    professor: 'Various',
    preRequisitos: ['Git básico'],
    objetivos: ['Colaborar no GitHub', 'Criar pull requests', 'Utilizar GitHub Actions'],
    tecnologiasRelacionadas: ['Git'],
    trilhas: ['novo-colaborador'],
    emDestaque: true
  },
  {
    id: 'alura-docker',
    titulo: 'Docker',
    descricao: 'Formação em Docker: containers, imagens, Docker Compose, volumes e rede.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '15h+',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-docker',
    embeddable: false,
    tags: ['docker', 'containers', 'devops', 'infra'],
    professor: 'Various',
    preRequisitos: ['Linha de comando básica'],
    objetivos: ['Criar containers com Docker', 'Utilizar Docker Compose', 'Gerenciar volumes e redes'],
    tecnologiasRelacionadas: ['DevOps', 'Linux', 'Kubernetes'],
    trilhas: ['analista-n2', 'desenvolvedor', 'lider-tecnico'],
    emDestaque: true
  },
  {
    id: 'alura-rest-api',
    titulo: 'REST API',
    descricao: 'Formação em REST API: design, métodos HTTP, status codes, versionamento e documentação.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '12h+',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-rest-api',
    embeddable: false,
    tags: ['rest', 'api', 'backend', 'http'],
    professor: 'Various',
    preRequisitos: ['C# ou JavaScript'],
    objetivos: ['Projetar APIs REST', 'Utilizar métodos HTTP corretamente', 'Documentar APIs'],
    tecnologiasRelacionadas: ['ASP.NET Core', 'Postman', 'JSON'],
    trilhas: ['desenvolvedor'],
    emDestaque: true
  },
  {
    id: 'alura-jwt',
    titulo: 'JWT',
    descricao: 'Formação em JWT: autenticação, autorização, tokens e boas práticas de segurança.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '8h+',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-jwt',
    embeddable: false,
    tags: ['jwt', 'seguranca', 'autenticacao', 'api'],
    professor: 'Various',
    preRequisitos: ['REST API', 'ASP.NET Core ou Node.js'],
    objetivos: ['Implementar autenticação JWT', 'Gerenciar tokens', 'Aplicar boas práticas de segurança'],
    tecnologiasRelacionadas: ['REST API', 'ASP.NET Core', 'OAuth'],
    trilhas: ['desenvolvedor'],
    emDestaque: true
  },
  {
    id: 'alura-windows-server',
    titulo: 'Windows Server',
    descricao: 'Formação em Windows Server: instalação, Active Directory, GPO, DNS e DHCP.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '20h+',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-windows-server',
    embeddable: false,
    tags: ['windows server', 'infra', 'active directory', 'dns'],
    professor: 'Various',
    preRequisitos: ['Conceitos de rede'],
    objetivos: ['Administrar Windows Server', 'Configurar Active Directory', 'Gerenciar GPOs e DNS'],
    tecnologiasRelacionadas: ['IIS', 'Redes', 'TCP/IP'],
    trilhas: ['analista-n1', 'analista-n2'],
    emDestaque: true
  },
  {
    id: 'alura-arquitetura',
    titulo: 'Arquitetura',
    descricao: 'Formação em Arquitetura de Software: Clean Architecture, CQRS, Event Sourcing e microsserviços.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '15h+',
    nivel: 'Avançado',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-arquitetura-software',
    embeddable: false,
    tags: ['arquitetura', 'clean architecture', 'cqrs', 'microsservicos'],
    professor: 'Various',
    preRequisitos: ['C#', 'ASP.NET Core', 'POO avançado'],
    objetivos: ['Aplicar Clean Architecture', 'Utilizar CQRS e Event Sourcing', 'Projetar microsserviços'],
    tecnologiasRelacionadas: ['SOLID', 'Design Patterns', 'Domain-Driven Design'],
    trilhas: ['lider-tecnico'],
    emDestaque: true
  },
  {
    id: 'alura-solid',
    titulo: 'SOLID',
    descricao: 'Formação em SOLID: os 5 princípios da programação orientada a objetos.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '10h+',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-solid',
    embeddable: false,
    tags: ['solid', 'boas praticas', 'oo', 'arquitetura'],
    professor: 'Various',
    preRequisitos: ['C# ou Java', 'POO'],
    objetivos: ['Compreender os 5 princípios SOLID', 'Aplicar SOLID no código diário', 'Melhorar design de classes'],
    tecnologiasRelacionadas: ['Design Patterns', 'Clean Architecture'],
    trilhas: ['desenvolvedor', 'lider-tecnico'],
    emDestaque: true
  },
  {
    id: 'alura-design-patterns',
    titulo: 'Design Patterns',
    descricao: 'Formação em Design Patterns: padrões GoF, Repository, Strategy, Factory e mais.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '15h+',
    nivel: 'Avançado',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-design-patterns',
    embeddable: false,
    tags: ['design patterns', 'gof', 'padroes', 'arquitetura'],
    professor: 'Various',
    preRequisitos: ['C# ou Java', 'POO avançado', 'SOLID'],
    objetivos: ['Utilizar padrões GoF', 'Implementar Repository e Strategy', 'Aplicar Factory e Singleton'],
    tecnologiasRelacionadas: ['SOLID', 'Clean Architecture', 'Domain-Driven Design'],
    trilhas: ['desenvolvedor', 'lider-tecnico'],
    emDestaque: true
  },
  {
    id: 'alura-clean-architecture',
    titulo: 'Clean Architecture',
    descricao: 'Formação em Clean Architecture: camadas, dependências, testes e boas práticas.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '12h+',
    nivel: 'Avançado',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-clean-architecture',
    embeddable: false,
    tags: ['clean architecture', 'arquitetura', 'testes', 'boas praticas'],
    professor: 'Various',
    preRequisitos: ['C#', 'ASP.NET Core', 'SOLID', 'Design Patterns'],
    objetivos: ['Estruturar projetos com Clean Architecture', 'Separar responsabilidades por camadas', 'Escrever testes unitários'],
    tecnologiasRelacionadas: ['SOLID', 'Design Patterns', 'Domain-Driven Design', 'Unit Testing'],
    trilhas: ['lider-tecnico'],
    emDestaque: true
  },
  {
    id: 'alura-devops',
    titulo: 'DevOps',
    descricao: 'Formação em DevOps: CI/CD, automação, monitoramento e boas práticas de entrega contínua.',
    categoria: 'alura',
    plataforma: 'Alura',
    autor: 'Alura',
    canal: 'Alura',
    duracao: '15h+',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.alura.com.br/formacao-devops',
    embeddable: false,
    tags: ['devops', 'ci/cd', 'automacao', 'entrega continua'],
    professor: 'Various',
    preRequisitos: ['Linux básico', 'Git'],
    objetivos: ['Implementar pipelines CI/CD', 'Automatizar deploys', 'Monitorar aplicações'],
    tecnologiasRelacionadas: ['Docker', 'Kubernetes', 'Jenkins', 'GitHub Actions'],
    trilhas: ['lider-tecnico'],
    emDestaque: true
  }
];

// ══════════════════════════════════════════════════════════
// YOUTUBE — Removido (manter apenas Alura)
// ══════════════════════════════════════════════════════════

export const cursosYouTube: Curso[] = [
  // ── DELPHI ──
  {
    id: 'yt-embarcadero-delphi',
    titulo: 'Embarcadero Brasil Delphi',
    descricao: 'Canal oficial da Embarcadero Brasil com tutoriais, dicas e novidades do Delphi.',
    categoria: 'delphi',
    plataforma: 'YouTube',
    autor: 'Embarcadero Brasil',
    canal: 'Embarcadero Brasil',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@EmbarcaderoDoBrasil',
    embeddable: false,
    tags: ['delphi', 'embarcadero', 'pascal', 'desktop'],
    trilhas: []
  },
  {
    id: 'yt-devmedia-delphi',
    titulo: 'DevMedia Delphi',
    descricao: 'Conteúdo Delphi no canal da DevMedia: tutoriais, artigos e vídeos completos.',
    categoria: 'delphi',
    plataforma: 'YouTube',
    autor: 'DevMedia',
    canal: 'DevMedia',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@devmedia.oficial',
    embeddable: false,
    tags: ['delphi', 'pascal', 'devmedia', 'programacao'],
    trilhas: []
  },

  // ── ANGULAR ──
  {
    id: 'yt-loiane-angular',
    titulo: 'Angular Completo - Loiane Groner',
    descricao: 'Playlist completa de Angular pela Loiane Groner: conceitos, componentes, rotas, formulários, HTTP e RxJS.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Loiane Groner',
    canal: 'Loiane Groner',
    duracao: 'Playlist completa',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/playlist?list=PLGxZ4Rq3BOBoSRcKWEdQACbUCNWLczg2G',
    playlistId: 'PLGxZ4Rq3BOBoSRcKWEdQACbUCNWLczg2G',
    embeddable: true,
    tags: ['angular', 'frontend', 'typescript', 'rxjs'],
    professor: 'Loiane Groner',
    preRequisitos: ['HTML', 'CSS', 'JavaScript básico'],
    objetivos: ['Dominar Angular do básico ao avançado', 'Criar aplicações SPA completas'],
    tecnologiasRelacionadas: ['TypeScript', 'RxJS', 'HTML', 'CSS'],
    trilhas: ['desenvolvedor'],
    emDestaque: true
  },
  {
    id: 'yt-cod3r-angular',
    titulo: 'Angular Completo - Cod3r',
    descricao: 'Curso completo de Angular pela equipe Cod3r: fundamentos, rotas, formulários e projetos práticos.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Cod3r',
    canal: 'Cod3r',
    duracao: 'Playlist completa',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/playlist?list=PLdPPE0hUkt0rPyAkdhHIIquKbwrGUkvw3',
    playlistId: 'PLdPPE0hUkt0rPyAkdhHIIquKbwrGUkvw3',
    embeddable: true,
    tags: ['angular', 'frontend', 'typescript', 'projeto'],
    professor: 'Equipe Cod3r',
    preRequisitos: ['HTML', 'CSS', 'JavaScript'],
    objetivos: ['Aprender Angular com projetos práticos', 'Entender arquitetura de componentes'],
    tecnologiasRelacionadas: ['TypeScript', 'JavaScript', 'HTML', 'CSS'],
    trilhas: ['desenvolvedor'],
    emDestaque: true
  },
  {
    id: 'yt-fernanda-kipper-angular',
    titulo: 'Angular - Fernanda Kipper',
    descricao: 'Conteúdo de Angular no canal Kipper Dev: tutoriais, dicas e boas práticas.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Fernanda Kipper',
    canal: 'Kipper Dev',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@kipperdev',
    embeddable: false,
    tags: ['angular', 'frontend', 'dicas', 'boas praticas'],
    professor: 'Fernanda Kipper',
    preRequisitos: ['HTML', 'CSS', 'JavaScript'],
    objetivos: ['Aprender Angular com abordagem prática', 'Conhecer dicas e atalhos'],
    tecnologiasRelacionadas: ['TypeScript', 'JavaScript'],
    trilhas: ['desenvolvedor']
  },
  {
    id: 'yt-hora-de-codar-angular',
    titulo: 'Angular - Hora de Codar',
    descricao: 'Playlist de Angular do canal Hora de Codar: do básico ao avançado com projetos.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Hora de Codar',
    canal: 'Hora de Codar',
    duracao: 'Playlist completa',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/playlist?list=PLnDvRpP8Bnex2GQEN0768_AxZg_RaIGmw',
    playlistId: 'PLnDvRpP8Bnex2GQEN0768_AxZg_RaIGmw',
    embeddable: true,
    tags: ['angular', 'frontend', 'projetos', 'pratico'],
    professor: 'Hora de Codar',
    preRequisitos: ['HTML', 'CSS', 'JavaScript'],
    objetivos: ['Desenvolver com Angular na prática', 'Criar projetos completos'],
    tecnologiasRelacionadas: ['TypeScript', 'HTML', 'CSS'],
    trilhas: ['desenvolvedor']
  },

  // ── TYPESCRIPT ──
  {
    id: 'yt-loiane-typescript',
    titulo: 'TypeScript - Loiane Groner',
    descricao: 'Canal da Loiane Groner com conteúdo de TypeScript: tipos, interfaces, generics e mais.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Loiane Groner',
    canal: 'Loiane Groner',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@loianegroner',
    embeddable: false,
    tags: ['typescript', 'frontend', 'tipos', 'interfaces'],
    professor: 'Loiane Groner',
    preRequisitos: ['JavaScript básico'],
    objetivos: ['Aprender TypeScript do básico ao avançado', 'Tipar código corretamente'],
    tecnologiasRelacionadas: ['JavaScript', 'Angular'],
    trilhas: ['desenvolvedor']
  },
  {
    id: 'yt-codigo-fonte-typescript',
    titulo: 'TypeScript - Código Fonte TV',
    descricao: 'Canal Código Fonte TV com tutoriais completos de TypeScript.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Código Fonte TV',
    canal: 'Código Fonte TV',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@codigofontetv',
    embeddable: false,
    tags: ['typescript', 'frontend', 'programacao'],
    professor: 'Código Fonte TV',
    preRequisitos: ['JavaScript'],
    objetivos: ['Dominar TypeScript', 'Utilizar tipos avançados'],
    tecnologiasRelacionadas: ['JavaScript', 'Angular', 'Node.js'],
    trilhas: ['desenvolvedor']
  },

  // ── HTML ──
  {
    id: 'yt-curso-em-video-html5',
    titulo: 'Curso em Vídeo - HTML5',
    descricao: 'Playlist completa de HTML5 pelo Curso em Vídeo: estrutura, semântica, formulários e boas práticas.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Curso em Vídeo',
    canal: 'Curso em Vídeo',
    duracao: 'Playlist completa',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n',
    playlistId: 'PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n',
    embeddable: true,
    tags: ['html', 'html5', 'frontend', 'web'],
    professor: 'Gustavo Guanabara',
    preRequisitos: [],
    objetivos: ['Aprender HTML5 do zero', 'Estruturar páginas web'],
    tecnologiasRelacionadas: ['CSS', 'JavaScript'],
    trilhas: ['novo-colaborador'],
    emDestaque: true
  },
  {
    id: 'yt-origamid-html',
    titulo: 'HTML - Origamid',
    descricao: 'Conteúdo de HTML no canal Origamid: tutoriais práticos e conceitos fundamentais.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Origamid',
    canal: 'Origamid',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@origamid',
    embeddable: false,
    tags: ['html', 'frontend', 'web', 'design'],
    professor: 'Origamid',
    preRequisitos: [],
    objetivos: ['Aprender HTML com foco em design', 'Entender semântica web'],
    tecnologiasRelacionadas: ['CSS', 'JavaScript'],
    trilhas: ['novo-colaborador']
  },

  // ── CSS ──
  {
    id: 'yt-curso-em-video-css3',
    titulo: 'Curso em Vídeo - CSS3',
    descricao: 'Playlist completa de CSS3 pelo Curso em Vídeo: seletores, flexbox, grid e responsividade.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Curso em Vídeo',
    canal: 'Curso em Vídeo',
    duracao: 'Playlist completa',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n',
    playlistId: 'PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n',
    embeddable: true,
    tags: ['css', 'css3', 'frontend', 'flexbox', 'grid'],
    professor: 'Gustavo Guanabara',
    preRequisitos: ['HTML básico'],
    objetivos: ['Dominar CSS3', 'Criar layouts responsivos'],
    tecnologiasRelacionadas: ['HTML', 'Bootstrap'],
    trilhas: ['novo-colaborador'],
    emDestaque: true
  },
  {
    id: 'yt-origamid-css',
    titulo: 'CSS - Origamid',
    descricao: 'Conteúdo de CSS no canal Origamid: tutoriais práticos de estilização web.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Origamid',
    canal: 'Origamid',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@origamid',
    embeddable: false,
    tags: ['css', 'frontend', 'web', 'estilizacao'],
    professor: 'Origamid',
    preRequisitos: ['HTML'],
    objetivos: ['Dominar CSS moderno', 'Criar layouts profissionais'],
    tecnologiasRelacionadas: ['HTML', 'JavaScript'],
    trilhas: ['novo-colaborador']
  },

  // ── BOOTSTRAP ──
  {
    id: 'yt-hora-de-codar-bootstrap',
    titulo: 'Bootstrap - Hora de Codar',
    descricao: 'Playlist de Bootstrap do canal Hora de Codar: grid, componentes e utilitários.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Hora de Codar',
    canal: 'Hora de Codar',
    duracao: 'Playlist completa',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/playlist?list=PLnDvRpP8Bnexu5wvxogy6N49_S5Xk8Cze',
    playlistId: 'PLnDvRpP8Bnexu5wvxogy6N49_S5Xk8Cze',
    embeddable: true,
    tags: ['bootstrap', 'frontend', 'css', 'ui'],
    professor: 'Hora de Codar',
    preRequisitos: ['HTML', 'CSS'],
    objetivos: ['Utilizar Bootstrap em projetos', 'Criar layouts responsivos rapidamente'],
    tecnologiasRelacionadas: ['HTML', 'CSS', 'JavaScript'],
    trilhas: []
  },
  {
    id: 'yt-cod3r-bootstrap',
    titulo: 'Bootstrap - Cod3r',
    descricao: 'Conteúdo de Bootstrap no canal Cod3r: tutoriais e projetos práticos.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Cod3r',
    canal: 'Cod3r',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@cod3r',
    embeddable: false,
    tags: ['bootstrap', 'frontend', 'css', 'framework'],
    professor: 'Equipe Cod3r',
    preRequisitos: ['HTML', 'CSS'],
    objetivos: ['Aprender Bootstrap na prática', 'Customizar o framework'],
    tecnologiasRelacionadas: ['HTML', 'CSS', 'JavaScript'],
    trilhas: []
  },

  // ── JAVASCRIPT ──
  {
    id: 'yt-curso-em-video-javascript',
    titulo: 'Curso em Vídeo - JavaScript',
    descricao: 'Playlist completa de JavaScript pelo Curso em Vídeo: fundamentos, DOM e eventos.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Curso em Vídeo',
    canal: 'Curso em Vídeo',
    duracao: 'Playlist completa',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    embeddable: true,
    tags: ['javascript', 'frontend', 'web', 'dom'],
    professor: 'Gustavo Guanabara',
    preRequisitos: ['HTML', 'CSS'],
    objetivos: ['Aprender JavaScript do zero', 'Manipular o DOM'],
    tecnologiasRelacionadas: ['HTML', 'CSS', 'TypeScript'],
    trilhas: ['novo-colaborador'],
    emDestaque: true
  },
  {
    id: 'yt-codigo-fonte-javascript',
    titulo: 'JavaScript - Código Fonte TV',
    descricao: 'Canal Código Fonte TV com tutoriais completos de JavaScript moderno.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Código Fonte TV',
    canal: 'Código Fonte TV',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@codigofontetv',
    embeddable: false,
    tags: ['javascript', 'frontend', 'es6', 'modern'],
    professor: 'Código Fonte TV',
    preRequisitos: ['HTML', 'CSS'],
    objetivos: ['Dominar JavaScript moderno', 'Utilizar ES6+'],
    tecnologiasRelacionadas: ['HTML', 'CSS', 'TypeScript'],
    trilhas: ['novo-colaborador']
  },
  {
    id: 'yt-filipe-deschamps-javascript',
    titulo: 'JavaScript - Filipe Deschamps',
    descricao: 'Conteúdo de JavaScript no canal Filipe Deschamps: dicas, tutoriais e boas práticas.',
    categoria: 'frontend',
    plataforma: 'YouTube',
    autor: 'Filipe Deschamps',
    canal: 'Filipe Deschamps',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@FilipeDeschamps',
    embeddable: false,
    tags: ['javascript', 'frontend', 'dicas', 'boas praticas'],
    professor: 'Filipe Deschamps',
    preRequisitos: ['HTML', 'CSS'],
    objetivos: ['Aprender JavaScript com dicas práticas', 'Conhecer boas práticas'],
    tecnologiasRelacionadas: ['HTML', 'CSS', 'Node.js'],
    trilhas: ['novo-colaborador']
  },

  // ── C# ──
  {
    id: 'yt-balta-csharp',
    titulo: 'C# - Balta.io',
    descricao: 'Conteúdo de C# no canal Balta.io: fundamentos, POO e recursos da linguagem.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Balta.io',
    canal: 'Balta.io',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@baltaio',
    embeddable: false,
    tags: ['c#', 'backend', 'dotnet', 'poo'],
    professor: 'Bira Alcântara',
    preRequisitos: ['Lógica de programação'],
    objetivos: ['Aprender C# com o Balta', 'Dominar POO em C#'],
    tecnologiasRelacionadas: ['.NET', 'ASP.NET Core', 'SQL Server'],
    trilhas: ['desenvolvedor']
  },
  {
    id: 'yt-macoratti-csharp',
    titulo: 'C# - Macoratti',
    descricao: 'Canal Macoratti com tutoriais completos de C#: fundamentos, LINQ, async e mais.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Macoratti',
    canal: 'Macoratti',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@josecarlosmacoratti',
    embeddable: false,
    tags: ['c#', 'backend', 'linq', 'async'],
    professor: 'Macoratti',
    preRequisitos: ['Lógica de programação'],
    objetivos: ['Dominar C# avançado', 'Utilizar LINQ e async/await'],
    tecnologiasRelacionadas: ['.NET', 'ASP.NET Core'],
    trilhas: ['desenvolvedor']
  },
  {
    id: 'yt-desenvolvedor-io-csharp',
    titulo: 'C# - Desenvolvedor.io',
    descricao: 'Canal Desenvolvedor.io com tutoriais de C# e .NET.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Desenvolvedor.io',
    canal: 'Desenvolvedor.io',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@desenvolvedorio',
    embeddable: false,
    tags: ['c#', 'backend', 'dotnet', 'tutoriais'],
    professor: 'Desenvolvedor.io',
    preRequisitos: ['Lógica de programação'],
    objetivos: ['Aprender C# e .NET', 'Desenvolver aplicações backend'],
    tecnologiasRelacionadas: ['.NET', 'ASP.NET Core', 'Entity Framework'],
    trilhas: ['desenvolvedor']
  },

  // ── ASP.NET CORE ──
  {
    id: 'yt-balta-aspnet-core',
    titulo: 'ASP.NET Core - Balta.io',
    descricao: 'Conteúdo de ASP.NET Core no canal Balta.io: Web API, EF Core e boas práticas.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Balta.io',
    canal: 'Balta.io',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@baltaio',
    embeddable: false,
    tags: ['aspnet', 'backend', 'api', 'ef core'],
    professor: 'Bira Alcântara',
    preRequisitos: ['C#', 'POO'],
    objetivos: ['Criar APIs com ASP.NET Core', 'Utilizar Entity Framework Core'],
    tecnologiasRelacionadas: ['C#', 'Entity Framework', 'SQL Server'],
    trilhas: ['desenvolvedor', 'analista-n2']
  },
  {
    id: 'yt-desenvolvedor-io-aspnet-core',
    titulo: 'ASP.NET Core - Desenvolvedor.io',
    descricao: 'Canal Desenvolvedor.io com tutoriais de ASP.NET Core e .NET.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Desenvolvedor.io',
    canal: 'Desenvolvedor.io',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@desenvolvedorio',
    embeddable: false,
    tags: ['aspnet', 'backend', 'dotnet', 'api'],
    professor: 'Desenvolvedor.io',
    preRequisitos: ['C#', '.NET'],
    objetivos: ['Aprender ASP.NET Core na prática', 'Criar APIs RESTful'],
    tecnologiasRelacionadas: ['C#', 'Entity Framework', 'SQL Server'],
    trilhas: ['desenvolvedor']
  },
  {
    id: 'yt-microsoft-reactor-aspnet-core',
    titulo: 'ASP.NET Core - Microsoft Reactor',
    descricao: 'Conteúdo de ASP.NET Core no canal Microsoft Reactor Brasil.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Microsoft Reactor Brasil',
    canal: 'Microsoft Reactor Brasil',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@MicrosoftReactor',
    embeddable: false,
    tags: ['aspnet', 'backend', 'microsoft', 'dotnet'],
    professor: 'Microsoft Reactor',
    preRequisitos: ['C#', '.NET'],
    objetivos: ['Conhecer novidades do ASP.NET Core', 'Aprender com especialistas Microsoft'],
    tecnologiasRelacionadas: ['C#', '.NET', 'Azure'],
    trilhas: ['desenvolvedor']
  },

  // ── SQL SERVER ──
  {
    id: 'yt-macoratti-sql-server',
    titulo: 'SQL Server - Macoratti',
    descricao: 'Canal Macoratti com tutoriais completos de SQL Server.',
    categoria: 'banco',
    plataforma: 'YouTube',
    autor: 'Macoratti',
    canal: 'Macoratti',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@josecarlosmacoratti',
    embeddable: false,
    tags: ['sql server', 'banco', 'tsql', 'consultas'],
    professor: 'Macoratti',
    preRequisitos: [],
    objetivos: ['Aprender SQL Server do zero', 'Escrever consultas SQL'],
    tecnologiasRelacionadas: ['C#', '.NET'],
    trilhas: ['analista-n1', 'analista-n2']
  },
  {
    id: 'yt-boson-sql-server',
    titulo: 'SQL Server - Bóson',
    descricao: 'Canal Bóson com tutoriais de SQL Server: consultas, procedures e administração.',
    categoria: 'banco',
    plataforma: 'YouTube',
    autor: 'Bóson',
    canal: 'Bóson',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@bosontreinamentos',
    embeddable: false,
    tags: ['sql server', 'banco', 'procedures', 'administracao'],
    professor: 'Bóson',
    preRequisitos: [],
    objetivos: ['Dominar SQL Server', 'Administrar bancos de dados'],
    tecnologiasRelacionadas: ['Windows Server', 'IIS'],
    trilhas: ['analista-n1', 'analista-n2']
  },
  {
    id: 'yt-microsoft-reactor-sql-server',
    titulo: 'SQL Server - Microsoft Reactor',
    descricao: 'Conteúdo de SQL Server no canal Microsoft Reactor Brasil.',
    categoria: 'banco',
    plataforma: 'YouTube',
    autor: 'Microsoft Reactor Brasil',
    canal: 'Microsoft Reactor Brasil',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@MicrosoftReactor',
    embeddable: false,
    tags: ['sql server', 'banco', 'microsoft', 'azure'],
    professor: 'Microsoft Reactor',
    preRequisitos: ['SQL básico'],
    objetivos: ['Conhecer SQL Server avançado', 'Integrar com Azure'],
    tecnologiasRelacionadas: ['Azure', '.NET'],
    trilhas: ['analista-n2']
  },

  // ── GIT ──
  {
    id: 'yt-curso-em-video-git',
    titulo: 'Git - Curso em Vídeo',
    descricao: 'Conteúdo de Git no canal Curso em Vídeo: versionamento e boas práticas.',
    categoria: 'versionamento',
    plataforma: 'YouTube',
    autor: 'Curso em Vídeo',
    canal: 'Curso em Vídeo',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@cursoemvideo',
    embeddable: false,
    tags: ['git', 'versionamento', 'controle-versao'],
    professor: 'Gustavo Guanabara',
    preRequisitos: [],
    objetivos: ['Aprender Git do zero', 'Versionar código corretamente'],
    tecnologiasRelacionadas: ['GitHub'],
    trilhas: ['novo-colaborador']
  },
  {
    id: 'yt-codigo-fonte-git',
    titulo: 'Git - Código Fonte TV',
    descricao: 'Conteúdo de Git no canal Código Fonte TV.',
    categoria: 'versionamento',
    plataforma: 'YouTube',
    autor: 'Código Fonte TV',
    canal: 'Código Fonte TV',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@codigofontetv',
    embeddable: false,
    tags: ['git', 'versionamento', 'github'],
    professor: 'Código Fonte TV',
    preRequisitos: [],
    objetivos: ['Dominar Git', 'Utilizar GitHub'],
    tecnologiasRelacionadas: ['GitHub'],
    trilhas: ['novo-colaborador']
  },
  {
    id: 'yt-filipe-deschamps-git',
    titulo: 'Git - Filipe Deschamps',
    descricao: 'Conteúdo de Git no canal Filipe Deschamps: dicas e boas práticas.',
    categoria: 'versionamento',
    plataforma: 'YouTube',
    autor: 'Filipe Deschamps',
    canal: 'Filipe Deschamps',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@FilipeDeschamps',
    embeddable: false,
    tags: ['git', 'versionamento', 'dicas'],
    professor: 'Filipe Deschamps',
    preRequisitos: [],
    objetivos: ['Aprender Git com dicas práticas', 'Evitar erros comuns'],
    tecnologiasRelacionadas: ['GitHub'],
    trilhas: ['novo-colaborador']
  },

  // ── DOCKER ──
  {
    id: 'yt-linuxtips-docker',
    titulo: 'Docker - LinuxTips',
    descricao: 'Canal LinuxTips com conteúdo completo de Docker e containers.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'LinuxTips',
    canal: 'LinuxTips',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@LinuxTips',
    embeddable: false,
    tags: ['docker', 'containers', 'devops', 'linux'],
    professor: 'LinuxTips',
    preRequisitos: ['Linux básico'],
    objetivos: ['Dominar Docker', 'Utilizar containers em produção'],
    tecnologiasRelacionadas: ['Linux', 'Kubernetes', 'DevOps'],
    trilhas: ['analista-n2', 'desenvolvedor']
  },
  {
    id: 'yt-full-cycle-docker',
    titulo: 'Docker - Full Cycle',
    descricao: 'Conteúdo de Docker no canal Full Cycle: conceitos, práticas e arquitetura de microsserviços.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Full Cycle',
    canal: 'Full Cycle',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@fullcycle',
    embeddable: false,
    tags: ['docker', 'containers', 'microsservicos', 'devops'],
    professor: 'Full Cycle',
    preRequisitos: ['Linux', 'Conceitos de rede'],
    objetivos: ['Utilizar Docker em microsserviços', 'Implementar ambientes de desenvolvimento'],
    tecnologiasRelacionadas: ['Kubernetes', 'CI/CD', 'Microsserviços'],
    trilhas: ['desenvolvedor', 'lider-tecnico']
  },
  {
    id: 'yt-codigo-fonte-docker',
    titulo: 'Docker - Código Fonte TV',
    descricao: 'Conteúdo de Docker no canal Código Fonte TV.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Código Fonte TV',
    canal: 'Código Fonte TV',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@codigofontetv',
    embeddable: false,
    tags: ['docker', 'containers', 'devops'],
    professor: 'Código Fonte TV',
    preRequisitos: ['Linha de comando básica'],
    objetivos: ['Aprender Docker do zero', 'Criar containers e imagens'],
    tecnologiasRelacionadas: ['Linux', 'DevOps'],
    trilhas: ['analista-n2']
  },

  // ── REST API ──
  {
    id: 'yt-desenvolvedor-io-rest-api',
    titulo: 'REST API - Desenvolvedor.io',
    descricao: 'Conteúdo de REST API no canal Desenvolvedor.io.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Desenvolvedor.io',
    canal: 'Desenvolvedor.io',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@desenvolvedorio',
    embeddable: false,
    tags: ['rest', 'api', 'backend', 'http'],
    professor: 'Desenvolvedor.io',
    preRequisitos: ['C# ou JavaScript'],
    objetivos: ['Aprender REST API na prática', 'Criar APIs RESTful'],
    tecnologiasRelacionadas: ['ASP.NET Core', 'Postman', 'JSON'],
    trilhas: ['desenvolvedor']
  },
  {
    id: 'yt-balta-rest-api',
    titulo: 'REST API - Balta.io',
    descricao: 'Conteúdo de REST API no canal Balta.io.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Balta.io',
    canal: 'Balta.io',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@baltaio',
    embeddable: false,
    tags: ['rest', 'api', 'backend', 'dotnet'],
    professor: 'Bira Alcântara',
    preRequisitos: ['C#'],
    objetivos: ['Dominar REST API', 'Implementar boas práticas'],
    tecnologiasRelacionadas: ['ASP.NET Core', 'C#'],
    trilhas: ['desenvolvedor']
  },
  {
    id: 'yt-codigo-fonte-rest-api',
    titulo: 'REST API - Código Fonte TV',
    descricao: 'Conteúdo de REST API no canal Código Fonte TV.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Código Fonte TV',
    canal: 'Código Fonte TV',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@codigofontetv',
    embeddable: false,
    tags: ['rest', 'api', 'backend', 'http'],
    professor: 'Código Fonte TV',
    preRequisitos: ['JavaScript ou C#'],
    objetivos: ['Aprender REST API', 'Documentar APIs'],
    tecnologiasRelacionadas: ['Postman', 'JSON'],
    trilhas: ['desenvolvedor']
  },

  // ── POSTMAN ──
  {
    id: 'yt-codigo-fonte-postman',
    titulo: 'Postman - Código Fonte TV',
    descricao: 'Conteúdo de Postman no canal Código Fonte TV.',
    categoria: 'ferramentas',
    plataforma: 'YouTube',
    autor: 'Código Fonte TV',
    canal: 'Código Fonte TV',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@codigofontetv',
    embeddable: false,
    tags: ['postman', 'api', 'ferramentas', 'testes'],
    professor: 'Código Fonte TV',
    preRequisitos: ['Conceitos de REST API'],
    objetivos: ['Utilizar Postman para testar APIs', 'Criar coleções e ambientes'],
    tecnologiasRelacionadas: ['REST API', 'HTTP'],
    trilhas: ['desenvolvedor']
  },
  {
    id: 'yt-desenvolvedor-io-postman',
    titulo: 'Postman - Desenvolvedor.io',
    descricao: 'Conteúdo de Postman no canal Desenvolvedor.io.',
    categoria: 'ferramentas',
    plataforma: 'YouTube',
    autor: 'Desenvolvedor.io',
    canal: 'Desenvolvedor.io',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@desenvolvedorio',
    embeddable: false,
    tags: ['postman', 'api', 'ferramentas', 'testes'],
    professor: 'Desenvolvedor.io',
    preRequisitos: ['Conceitos de REST API'],
    objetivos: ['Dominar Postman', 'Automatizar testes de API'],
    tecnologiasRelacionadas: ['REST API', 'HTTP'],
    trilhas: ['desenvolvedor']
  },

  // ── JSON ──
  {
    id: 'yt-codigo-fonte-json',
    titulo: 'JSON - Código Fonte TV',
    descricao: 'Conteúdo de JSON no canal Código Fonte TV.',
    categoria: 'ferramentas',
    plataforma: 'YouTube',
    autor: 'Código Fonte TV',
    canal: 'Código Fonte TV',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@codigofontetv',
    embeddable: false,
    tags: ['json', 'dados', 'api', 'ferramentas'],
    professor: 'Código Fonte TV',
    preRequisitos: [],
    objetivos: ['Aprender JSON', 'Utilizar JSON em APIs'],
    tecnologiasRelacionadas: ['REST API', 'JavaScript'],
    trilhas: ['desenvolvedor']
  },
  {
    id: 'yt-balta-json',
    titulo: 'JSON - Balta.io',
    descricao: 'Conteúdo de JSON no canal Balta.io.',
    categoria: 'ferramentas',
    plataforma: 'YouTube',
    autor: 'Balta.io',
    canal: 'Balta.io',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@baltaio',
    embeddable: false,
    tags: ['json', 'dados', 'api'],
    professor: 'Bira Alcântara',
    preRequisitos: [],
    objetivos: ['Entender estrutura JSON', 'Utilizar JSON em aplicações'],
    tecnologiasRelacionadas: ['REST API', 'C#'],
    trilhas: ['desenvolvedor']
  },

  // ── WINDOWS SERVER ──
  {
    id: 'yt-boson-windows-server',
    titulo: 'Windows Server - Bóson',
    descricao: 'Canal Bóson com tutoriais completos de Windows Server.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Bóson',
    canal: 'Bóson',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@bosontreinamentos',
    embeddable: false,
    tags: ['windows server', 'infra', 'active directory', 'gpo'],
    professor: 'Bóson',
    preRequisitos: ['Conceitos de rede'],
    objetivos: ['Administrar Windows Server', 'Configurar AD e GPO'],
    tecnologiasRelacionadas: ['IIS', 'DNS', 'DHCP'],
    trilhas: ['analista-n1', 'analista-n2']
  },
  {
    id: 'yt-professor-ramos-windows-server',
    titulo: 'Windows Server - Professor Ramos',
    descricao: 'Canal Professor Ramos com tutoriais de Windows Server e infraestrutura.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Professor Ramos',
    canal: 'Professor Ramos',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@ProfessorRamos',
    embeddable: false,
    tags: ['windows server', 'infra', 'administracao'],
    professor: 'Professor Ramos',
    preRequisitos: ['Conceitos de rede'],
    objetivos: ['Administrar Windows Server', 'Gerenciar serviços de rede'],
    tecnologiasRelacionadas: ['IIS', 'DNS', 'DHCP'],
    trilhas: ['analista-n1', 'analista-n2']
  },

  // ── IIS ──
  {
    id: 'yt-boson-iis',
    titulo: 'IIS - Bóson',
    descricao: 'Conteúdo de IIS no canal Bóson.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Bóson',
    canal: 'Bóson',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@bosontreinamentos',
    embeddable: false,
    tags: ['iis', 'infra', 'web', 'windows'],
    professor: 'Bóson',
    preRequisitos: ['Windows Server'],
    objetivos: ['Administrar IIS', 'Configurar sites e pools'],
    tecnologiasRelacionadas: ['Windows Server', 'ASP.NET Core'],
    trilhas: ['analista-n2']
  },
  {
    id: 'yt-microsoft-reactor-iis',
    titulo: 'IIS - Microsoft Reactor',
    descricao: 'Conteúdo de IIS no canal Microsoft Reactor Brasil.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Microsoft Reactor Brasil',
    canal: 'Microsoft Reactor Brasil',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@MicrosoftReactor',
    embeddable: false,
    tags: ['iis', 'infra', 'microsoft', 'web'],
    professor: 'Microsoft Reactor',
    preRequisitos: ['Windows Server'],
    objetivos: ['Aprender IIS com especialistas Microsoft', 'Configurar ambientes de produção'],
    tecnologiasRelacionadas: ['Windows Server', 'ASP.NET Core'],
    trilhas: ['analista-n2']
  },

  // ── REDES ──
  {
    id: 'yt-boson-redes',
    titulo: 'Redes - Bóson',
    descricao: 'Canal Bóson com tutoriais completos de Redes de Computadores.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Bóson',
    canal: 'Bóson',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@bosontreinamentos',
    embeddable: false,
    tags: ['redes', 'tcp/ip', 'infra', 'roteamento'],
    professor: 'Bóson',
    preRequisitos: [],
    objetivos: ['Aprender redes do zero', 'Configurar roteamento'],
    tecnologiasRelacionadas: ['TCP/IP', 'Windows Server'],
    trilhas: ['analista-n1']
  },
  {
    id: 'yt-professor-ramos-redes',
    titulo: 'Redes - Professor Ramos',
    descricao: 'Canal Professor Ramos com tutoriais de Redes de Computadores.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Professor Ramos',
    canal: 'Professor Ramos',
    duracao: 'Canal completo',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@ProfessorRamos',
    embeddable: false,
    tags: ['redes', 'infra', 'configuracao'],
    professor: 'Professor Ramos',
    preRequisitos: [],
    objetivos: ['Dominar conceitos de rede', 'Configurar equipamentos'],
    tecnologiasRelacionadas: ['TCP/IP', 'Windows Server'],
    trilhas: ['analista-n1']
  },

  // ── TCP/IP ──
  {
    id: 'yt-boson-tcpip',
    titulo: 'TCP/IP - Bóson',
    descricao: 'Conteúdo de TCP/IP no canal Bóson.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Bóson',
    canal: 'Bóson',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@bosontreinamentos',
    embeddable: false,
    tags: ['tcp/ip', 'redes', 'protocolos', 'subnet'],
    professor: 'Bóson',
    preRequisitos: ['Conceitos de rede'],
    objetivos: ['Dominar TCP/IP', 'Configurar subnets'],
    tecnologiasRelacionadas: ['Redes', 'Windows Server'],
    trilhas: ['analista-n1', 'analista-n2']
  },
  {
    id: 'yt-professor-ramos-tcpip',
    titulo: 'TCP/IP - Professor Ramos',
    descricao: 'Conteúdo de TCP/IP no canal Professor Ramos.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Professor Ramos',
    canal: 'Professor Ramos',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@ProfessorRamos',
    embeddable: false,
    tags: ['tcp/ip', 'redes', 'protocolos'],
    professor: 'Professor Ramos',
    preRequisitos: ['Conceitos de rede'],
    objetivos: ['Aprofundar conhecimento em TCP/IP', 'Resolver problemas de rede'],
    tecnologiasRelacionadas: ['Redes', 'Windows Server'],
    trilhas: ['analista-n1', 'analista-n2']
  },

  // ── ARQUITETURA / CLEAN ARCHITECTURE ──
  {
    id: 'yt-full-cycle-clean-architecture',
    titulo: 'Clean Architecture - Full Cycle',
    descricao: 'Conteúdo de Clean Architecture no canal Full Cycle.',
    categoria: 'arquitetura',
    plataforma: 'YouTube',
    autor: 'Full Cycle',
    canal: 'Full Cycle',
    duracao: 'Canal completo',
    nivel: 'Avançado',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@fullcycle',
    embeddable: false,
    tags: ['clean architecture', 'arquitetura', 'microsservicos'],
    professor: 'Full Cycle',
    preRequisitos: ['C#', 'ASP.NET Core', 'SOLID'],
    objetivos: ['Aplicar Clean Architecture', 'Projetar aplicações escaláveis'],
    tecnologiasRelacionadas: ['SOLID', 'Design Patterns', 'DDD'],
    trilhas: ['lider-tecnico']
  },
  {
    id: 'yt-desenvolvedor-io-arquitetura',
    titulo: 'Arquitetura - Desenvolvedor.io',
    descricao: 'Conteúdo de Arquitetura de Software no canal Desenvolvedor.io.',
    categoria: 'arquitetura',
    plataforma: 'YouTube',
    autor: 'Desenvolvedor.io',
    canal: 'Desenvolvedor.io',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@desenvolvedorio',
    embeddable: false,
    tags: ['arquitetura', 'clean architecture', 'design'],
    professor: 'Desenvolvedor.io',
    preRequisitos: ['C#', '.NET'],
    objetivos: ['Aprender arquitetura de software', 'Aplicar Clean Architecture'],
    tecnologiasRelacionadas: ['SOLID', 'Design Patterns'],
    trilhas: ['lider-tecnico']
  },

  // ── SOLID ──
  {
    id: 'yt-balta-solid',
    titulo: 'SOLID - Balta.io',
    descricao: 'Conteúdo de SOLID no canal Balta.io.',
    categoria: 'arquitetura',
    plataforma: 'YouTube',
    autor: 'Balta.io',
    canal: 'Balta.io',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@baltaio',
    embeddable: false,
    tags: ['solid', 'boas praticas', 'oo', 'arquitetura'],
    professor: 'Bira Alcântara',
    preRequisitos: ['C#', 'POO'],
    objetivos: ['Dominar os 5 princípios SOLID', 'Aplicar SOLID no código'],
    tecnologiasRelacionadas: ['Design Patterns', 'Clean Architecture'],
    trilhas: ['desenvolvedor', 'lider-tecnico']
  },
  {
    id: 'yt-full-cycle-solid',
    titulo: 'SOLID - Full Cycle',
    descricao: 'Conteúdo de SOLID no canal Full Cycle.',
    categoria: 'arquitetura',
    plataforma: 'YouTube',
    autor: 'Full Cycle',
    canal: 'Full Cycle',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@fullcycle',
    embeddable: false,
    tags: ['solid', 'boas praticas', 'arquitetura'],
    professor: 'Full Cycle',
    preRequisitos: ['C# ou Java', 'POO'],
    objetivos: ['Aplicar SOLID em projetos reais', 'Melhorar design de código'],
    tecnologiasRelacionadas: ['Design Patterns', 'Clean Architecture'],
    trilhas: ['desenvolvedor', 'lider-tecnico']
  },

  // ── DESIGN PATTERNS ──
  {
    id: 'yt-balta-design-patterns',
    titulo: 'Design Patterns - Balta.io',
    descricao: 'Conteúdo de Design Patterns no canal Balta.io.',
    categoria: 'arquitetura',
    plataforma: 'YouTube',
    autor: 'Balta.io',
    canal: 'Balta.io',
    duracao: 'Canal completo',
    nivel: 'Avançado',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@baltaio',
    embeddable: false,
    tags: ['design patterns', 'gof', 'padroes'],
    professor: 'Bira Alcântara',
    preRequisitos: ['C#', 'POO avançado', 'SOLID'],
    objetivos: ['Utilizar padrões GoF', 'Implementar Repository e Strategy'],
    tecnologiasRelacionadas: ['SOLID', 'Clean Architecture'],
    trilhas: ['desenvolvedor', 'lider-tecnico']
  },
  {
    id: 'yt-macoratti-design-patterns',
    titulo: 'Design Patterns - Macoratti',
    descricao: 'Conteúdo de Design Patterns no canal Macoratti.',
    categoria: 'arquitetura',
    plataforma: 'YouTube',
    autor: 'Macoratti',
    canal: 'Macoratti',
    duracao: 'Canal completo',
    nivel: 'Avançado',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@josecarlosmacoratti',
    embeddable: false,
    tags: ['design patterns', 'gof', 'padroes', 'c#'],
    professor: 'Macoratti',
    preRequisitos: ['C#', 'POO avançado'],
    objetivos: ['Aprender Design Patterns com C#', 'Implementar padrões clássicos'],
    tecnologiasRelacionadas: ['SOLID', 'C#'],
    trilhas: ['desenvolvedor']
  },

  // ── DEVOPS ──
  {
    id: 'yt-linuxtips-devops',
    titulo: 'DevOps - LinuxTips',
    descricao: 'Conteúdo de DevOps no canal LinuxTips.',
    categoria: 'arquitetura',
    plataforma: 'YouTube',
    autor: 'LinuxTips',
    canal: 'LinuxTips',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@LinuxTips',
    embeddable: false,
    tags: ['devops', 'ci/cd', 'automacao', 'linux'],
    professor: 'LinuxTips',
    preRequisitos: ['Linux', 'Docker'],
    objetivos: ['Implementar DevOps', 'Automatizar entregas'],
    tecnologiasRelacionadas: ['Docker', 'Kubernetes', 'CI/CD'],
    trilhas: ['lider-tecnico']
  },
  {
    id: 'yt-full-cycle-devops',
    titulo: 'DevOps - Full Cycle',
    descricao: 'Conteúdo de DevOps no canal Full Cycle.',
    categoria: 'arquitetura',
    plataforma: 'YouTube',
    autor: 'Full Cycle',
    canal: 'Full Cycle',
    duracao: 'Canal completo',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/@fullcycle',
    embeddable: false,
    tags: ['devops', 'ci/cd', 'automacao', 'deploy'],
    professor: 'Full Cycle',
    preRequisitos: ['Linux', 'Docker'],
    objetivos: ['Dominar DevOps', 'Implementar pipelines CI/CD'],
    tecnologiasRelacionadas: ['Docker', 'Kubernetes', 'GitHub Actions'],
    trilhas: ['lider-tecnico']
  },
  {
    id: 'yt-o-que-e-api',
    titulo: 'O que é API? O que é REST? O que é RESTful? Uma introdução para iniciantes em programação',
    descricao: 'Vídeo do canal Serliv (Daniel Tapias Morales) que explica o que é API, REST e RESTful de forma didática para iniciantes.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Serliv - Daniel Tapias Morales',
    canal: 'Serliv',
    duracao: '21 min',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/watch?v=umaXYEbd5vA',
    videoId: 'umaXYEbd5vA',
    embeddable: true,
    tags: ['api', 'rest', 'restful', 'http', 'backend'],
    professor: 'Daniel Tapias Morales',
    preRequisitos: ['Nenhum'],
    objetivos: ['Entender o que é uma API', 'Entender REST e RESTful'],
    tecnologiasRelacionadas: ['HTTP', 'REST', 'JSON'],
    trilhas: ['apis-integracoes', 'desenvolvimento']
  },
  {
    id: 'yt-o-que-e-api-2min',
    titulo: 'O que é API (em 2 minutos)',
    descricao: 'Explicação curta e direta do Yudi Ganeko sobre o que é uma API e para que ela serve.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Yudi Ganeko',
    canal: 'Yudi Ganeko',
    duracao: '2 min',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/watch?v=Q-lyQ7BdDXE',
    videoId: 'Q-lyQ7BdDXE',
    embeddable: true,
    tags: ['api', 'conceitos', 'backend'],
    professor: 'Yudi Ganeko',
    preRequisitos: ['Nenhum'],
    objetivos: ['Entender o que é uma API'],
    tecnologiasRelacionadas: ['HTTP'],
    trilhas: ['apis-integracoes', 'desenvolvimento']
  },
  {
    id: 'yt-api-rest-mayk',
    titulo: 'O que é API? REST e RESTful? | Mayk Brito',
    descricao: 'Vídeo da Rocketseat com Mayk Brito explicando APIs, REST e RESTful com exemplos práticos.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Rocketseat',
    canal: 'Rocketseat',
    duracao: '20 min',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/watch?v=ghTrp1x_1As',
    videoId: 'ghTrp1x_1As',
    embeddable: true,
    tags: ['api', 'rest', 'restful', 'backend', 'rocketseat'],
    professor: 'Mayk Brito',
    preRequisitos: ['Noções de programação'],
    objetivos: ['Entender APIs REST', 'Entender a diferença entre REST e RESTful'],
    tecnologiasRelacionadas: ['HTTP', 'REST', 'JSON'],
    trilhas: ['apis-integracoes', 'desenvolvimento']
  },
  {
    id: 'yt-rest-patch-put',
    titulo: 'O que é REST? (POST vs PATCH vs PUT)',
    descricao: 'Vídeo do Augusto Galego que explica o conceito de REST e a diferença entre os verbos HTTP POST, PATCH e PUT.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Augusto Galego',
    canal: 'Augusto Galego',
    duracao: '8 min',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/watch?v=HsDUsdYlup0',
    videoId: 'HsDUsdYlup0',
    embeddable: true,
    tags: ['rest', 'http', 'metodos', 'backend'],
    professor: 'Augusto Galego',
    preRequisitos: ['Noções de API'],
    objetivos: ['Entender REST', 'Diferenciar POST, PATCH e PUT'],
    tecnologiasRelacionadas: ['HTTP', 'REST'],
    trilhas: ['apis-integracoes', 'desenvolvimento']
  },
  {
    id: 'yt-cors-front-back',
    titulo: 'O que é CORS? Análise frontend e backend',
    descricao: 'Vídeo do Augusto Galego que explica o que é CORS e como ele se comporta no frontend e no backend.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Augusto Galego',
    canal: 'Augusto Galego',
    duracao: '12 min',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/watch?v=0gXiTWMikDU',
    videoId: '0gXiTWMikDU',
    embeddable: true,
    tags: ['cors', 'http', 'seguranca', 'frontend', 'backend'],
    professor: 'Augusto Galego',
    preRequisitos: ['Noções de HTTP e APIs'],
    objetivos: ['Entender o que é CORS', 'Identificar e tratar erros de CORS'],
    tecnologiasRelacionadas: ['HTTP', 'CORS'],
    trilhas: ['apis-integracoes', 'desenvolvimento']
  },
  {
    id: 'yt-cors-pratica',
    titulo: 'Como funciona o CORS na prática',
    descricao: 'Vídeo do Prof. Rogério Napoleão Jr. demonstrando na prática como o CORS funciona e quando ele bloqueia requisições.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Prof. Rogério Napoleão Jr.',
    canal: 'Prof. Rogério Napoleão Jr.',
    duracao: '22 min',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/watch?v=1V1qkh6K8Gg',
    videoId: '1V1qkh6K8Gg',
    embeddable: true,
    tags: ['cors', 'http', 'backend'],
    professor: 'Prof. Rogério Napoleão Jr.',
    preRequisitos: ['Noções de HTTP e APIs'],
    objetivos: ['Entender CORS na prática', 'Configurar CORS no backend'],
    tecnologiasRelacionadas: ['HTTP', 'CORS'],
    trilhas: ['apis-integracoes', 'desenvolvimento']
  },
  {
    id: 'yt-cors-2min',
    titulo: 'CORS o que é e como resolver o problema de CORS em 2 minutos',
    descricao: 'Vídeo rápido do Wygor Code mostrando o que é CORS e como resolver o problema em poucos minutos.',
    categoria: 'backend',
    plataforma: 'YouTube',
    autor: 'Wygor Code',
    canal: 'Wygor Code',
    duracao: '2 min',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/watch?v=bgx-aBs6Pk0',
    videoId: 'bgx-aBs6Pk0',
    embeddable: true,
    tags: ['cors', 'http', 'backend'],
    professor: 'Wygor Code',
    preRequisitos: ['Noções de HTTP e APIs'],
    objetivos: ['Entender CORS', 'Resolver problemas de CORS'],
    tecnologiasRelacionadas: ['HTTP', 'CORS'],
    trilhas: ['apis-integracoes', 'desenvolvimento']
  },
  {
    id: 'yt-curso-sql-server-completo',
    titulo: 'Curso Completo de SQL com SQL Server para Iniciantes do Básico ao Avançado',
    descricao: 'Curso completo do Bóson Treinamentos ensinando SQL com SQL Server do básico ao avançado, ideal para começar com bancos de dados.',
    categoria: 'banco',
    plataforma: 'YouTube',
    autor: 'Bóson Treinamentos',
    canal: 'Bóson Treinamentos',
    duracao: '7h',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/watch?v=KOhd3R5kLks&t=49s',
    videoId: 'KOhd3R5kLks',
    embeddable: true,
    tags: ['sql', 'sql server', 'banco de dados', 'consultas'],
    professor: 'Bóson Treinamentos',
    preRequisitos: ['Nenhum'],
    objetivos: ['Dominar SQL', 'Trabalhar com SQL Server'],
    tecnologiasRelacionadas: ['SQL', 'SQL Server'],
    trilhas: ['banco-de-dados']
  },
  {
    id: 'yt-curso-redes-completo',
    titulo: 'Curso de Redes de Computadores (Completo)',
    descricao: 'Playlist completa de redes de computadores, do básico ao avançado, cobrindo modelos OSI/TCP-IP, protocolos, cabeamento e infraestrutura de rede.',
    categoria: 'infra',
    plataforma: 'YouTube',
    autor: 'Curso de Redes de Computadores',
    canal: 'Curso de Redes de Computadores',
    duracao: 'Playlist completa',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/playlist?list=PLF9vK2NfbRJtROPfTFQcJcB47STXDfYeX',
    videoId: '8V1MeQ4LgbQ',
    playlistId: 'PLF9vK2NfbRJtROPfTFQcJcB47STXDfYeX',
    embeddable: true,
    tags: ['redes', 'osi', 'tcp ip', 'protocolos', 'infraestrutura'],
    professor: 'Curso de Redes de Computadores',
    preRequisitos: ['Nenhum'],
    objetivos: ['Entender modelos OSI e TCP/IP', 'Configurar infraestrutura de rede'],
    tecnologiasRelacionadas: ['TCP/IP', 'DNS', 'DHCP'],
    trilhas: ['redes']
  },
  {
    id: 'yt-postman-qa',
    titulo: 'Testes de API com Postman [Tutorial Completo para QAs]',
    descricao: 'Tutorial completo do canal Many - QA mostrando como testar APIs com o Postman, criando coleções, variáveis e automações de testes.',
    categoria: 'ferramentas',
    plataforma: 'YouTube',
    autor: 'Many - QA | Migração para TI',
    canal: 'Many - QA | Migração para TI',
    duracao: '1h',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/watch?v=p5qoiuFA4hs',
    videoId: 'p5qoiuFA4hs',
    embeddable: true,
    tags: ['postman', 'testes', 'api', 'qa'],
    professor: 'Many - QA',
    preRequisitos: ['Noções de APIs REST'],
    objetivos: ['Testar APIs com Postman', 'Criar coleções e automações'],
    tecnologiasRelacionadas: ['Postman', 'REST'],
    trilhas: ['apis-integracoes', 'ferramentas']
  }
];

// ══════════════════════════════════════════════════════════
// CURSO EM VÍDEO — Cursos gratuitos (Gustavo Guanabara)
// ══════════════════════════════════════════════════════════

export const cursosCursoEmVideo: Curso[] = [
  {
    id: 'cev-mysql',
    titulo: 'Curso de MySQL',
    descricao: 'Curso gratuito do professor Gustavo Guanabara: instalação, modelagem de dados e consultas SQL no MySQL.',
    categoria: 'curso-em-video',
    plataforma: 'Curso em Vídeo',
    autor: 'Curso em Vídeo',
    canal: 'Curso em Vídeo',
    duracao: '40 horas',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.cursoemvideo.com/curso/mysql/',
    playlistId: 'PLHz_AreHm4dkBs-795Dsgvau_ekxg8g1r',
    embeddable: true,
    tags: ['mysql', 'sql', 'banco de dados', 'curso em video'],
    professor: 'Gustavo Guanabara',
    preRequisitos: ['Lógica de programação'],
    objetivos: ['Modelar banco de dados', 'Criar consultas SQL'],
    tecnologiasRelacionadas: ['MySQL', 'SQL', 'phpMyAdmin'],
    trilhas: ['banco-de-dados'],
    emDestaque: true
  },
  {
    id: 'cev-algoritmos',
    titulo: 'Curso de Algoritmos',
    descricao: 'Curso gratuito de lógica de programação e algoritmos do professor Gustavo Guanabara, ideal para quem está começando.',
    categoria: 'curso-em-video',
    plataforma: 'Curso em Vídeo',
    autor: 'Curso em Vídeo',
    canal: 'Curso em Vídeo',
    duracao: '40 horas',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.cursoemvideo.com/curso/curso-de-algoritmo',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    embeddable: true,
    tags: ['algoritmos', 'logica', 'programacao', 'curso em video'],
    professor: 'Gustavo Guanabara',
    preRequisitos: ['Nenhum'],
    objetivos: ['Aprender lógica de programação', 'Criar algoritmos'],
    tecnologiasRelacionadas: ['Portugol', 'Algoritmos'],
    trilhas: ['fundamentos'],
    emDestaque: true
  },
  {
    id: 'cev-python3',
    titulo: 'Python 3 - Mundo 1',
    descricao: 'Curso gratuito de Python 3 (Mundo 1) do professor Gustavo Guanabara: fundamentos da linguagem e primeiros programas.',
    categoria: 'curso-em-video',
    plataforma: 'Curso em Vídeo',
    autor: 'Curso em Vídeo',
    canal: 'Curso em Vídeo',
    duracao: '40 horas',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6',
    playlistId: 'PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6',
    embeddable: true,
    tags: ['python', 'programacao', 'curso em video'],
    professor: 'Gustavo Guanabara',
    preRequisitos: ['Lógica de programação'],
    objetivos: ['Aprender a linguagem Python', 'Criar scripts e programas'],
    tecnologiasRelacionadas: ['Python'],
    trilhas: ['fundamentos'],
    emDestaque: true
  },
  {
    id: 'cev-linux',
    titulo: 'Linux - Primeiros Passos',
    descricao: 'Curso gratuito de Linux do professor Gustavo Guanabara: instalação, principais comandos e administração básica.',
    categoria: 'curso-em-video',
    plataforma: 'Curso em Vídeo',
    autor: 'Curso em Vídeo',
    canal: 'Curso em Vídeo',
    duracao: '10 horas',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlIXleu20uwPWFOSswqLYbV',
    playlistId: 'PLHz_AreHm4dlIXleu20uwPWFOSswqLYbV',
    embeddable: true,
    tags: ['linux', 'sistemas operacionais', 'comandos', 'curso em video'],
    professor: 'Gustavo Guanabara',
    preRequisitos: ['Nenhum'],
    objetivos: ['Instalar o Linux', 'Usar os principais comandos'],
    tecnologiasRelacionadas: ['Linux', 'Terminal'],
    trilhas: ['sistemas-operacionais']
  }
];

// ══════════════════════════════════════════════════════════
// MICROSOFT LEARN — Trilhas e módulos gratuitos
// ══════════════════════════════════════════════════════════

export const cursosMicrosoftLearn: Curso[] = [
  {
    id: 'mslearn-sql-server',
    titulo: 'Introdução ao SQL Server 2025',
    descricao: 'Módulo oficial da Microsoft Learn: edições do SQL Server, instalação e primeiros passos com o banco de dados.',
    categoria: 'microsoft-learn',
    plataforma: 'Microsoft Learn',
    autor: 'Microsoft',
    canal: 'Microsoft Learn',
    duracao: '1h28min',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://learn.microsoft.com/pt-br/training/modules/introduction-to-sql-server/',
    embeddable: false,
    tags: ['sql server', 'banco de dados', 'microsoft learn'],
    professor: 'Microsoft Learn',
    preRequisitos: ['Noções de banco de dados'],
    objetivos: ['Conhecer o SQL Server 2025', 'Instalar e configurar'],
    tecnologiasRelacionadas: ['SQL Server'],
    trilhas: ['banco-de-dados'],
    emDestaque: true
  },
  {
    id: 'mslearn-windows-server',
    titulo: 'Windows Server - Fundamentos',
    descricao: 'Conceitos e fundamentos do Windows Server pela Microsoft Learn, incluindo AD, DNS e administração de servidores.',
    categoria: 'microsoft-learn',
    plataforma: 'Microsoft Learn',
    autor: 'Microsoft',
    canal: 'Microsoft Learn',
    duracao: 'Módulos',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://learn.microsoft.com/pt-br/training/browse/?products=windows-server',
    embeddable: false,
    tags: ['windows server', 'infraestrutura', 'microsoft learn'],
    professor: 'Microsoft Learn',
    preRequisitos: ['Noções de redes'],
    objetivos: ['Administrar Windows Server', 'Configurar AD e DNS'],
    tecnologiasRelacionadas: ['Windows Server', 'Active Directory'],
    trilhas: ['infraestrutura', 'sistemas-operacionais']
  },
  {
    id: 'mslearn-iis',
    titulo: 'IIS e Hospedagem de Aplicações',
    descricao: 'Aprenda a configurar e gerenciar o Internet Information Services (IIS) na Microsoft Learn.',
    categoria: 'microsoft-learn',
    plataforma: 'Microsoft Learn',
    autor: 'Microsoft',
    canal: 'Microsoft Learn',
    duracao: 'Módulos',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://learn.microsoft.com/pt-br/training/browse/?products=iis',
    embeddable: false,
    tags: ['iis', 'windows server', 'infraestrutura', 'microsoft learn'],
    professor: 'Microsoft Learn',
    preRequisitos: ['Windows Server'],
    objetivos: ['Configurar sites no IIS', 'Publicar aplicações'],
    tecnologiasRelacionadas: ['IIS', 'Windows Server'],
    trilhas: ['infraestrutura']
  },
  {
    id: 'mslearn-powershell',
    titulo: 'PowerShell - Fundamentos',
    descricao: 'Automatize tarefas administrativas com PowerShell pela Microsoft Learn: comandos, scripts e módulos.',
    categoria: 'microsoft-learn',
    plataforma: 'Microsoft Learn',
    autor: 'Microsoft',
    canal: 'Microsoft Learn',
    duracao: 'Módulos',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://learn.microsoft.com/pt-br/training/browse/?products=powershell',
    embeddable: false,
    tags: ['powershell', 'scripting', 'automacao', 'microsoft learn'],
    professor: 'Microsoft Learn',
    preRequisitos: ['Noções de terminal'],
    objetivos: ['Usar comandos do PowerShell', 'Criar scripts'],
    tecnologiasRelacionadas: ['PowerShell'],
    trilhas: ['sistemas-operacionais']
  },
  {
    id: 'mslearn-docker',
    titulo: 'Containers com Docker',
    descricao: 'Introdução a containers e ao Docker pela Microsoft Learn: imagens, volumes e orquestração básica.',
    categoria: 'microsoft-learn',
    plataforma: 'Microsoft Learn',
    autor: 'Microsoft',
    canal: 'Microsoft Learn',
    duracao: 'Módulos',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://learn.microsoft.com/pt-br/training/browse/?products=azure-container-instances&terms=docker',
    embeddable: false,
    tags: ['docker', 'containers', 'devops', 'microsoft learn'],
    professor: 'Microsoft Learn',
    preRequisitos: ['Noções de DevOps'],
    objetivos: ['Criar imagens Docker', 'Executar containers'],
    tecnologiasRelacionadas: ['Docker', 'Containers'],
    trilhas: ['infraestrutura']
  },
  {
    id: 'mslearn-aspnet-webapi',
    titulo: 'Criar APIs com ASP.NET Core',
    descricao: 'Crie APIs REST com ASP.NET Core pela Microsoft Learn, incluindo Minimal APIs e boas práticas.',
    categoria: 'microsoft-learn',
    plataforma: 'Microsoft Learn',
    autor: 'Microsoft',
    canal: 'Microsoft Learn',
    duracao: 'Módulos',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://learn.microsoft.com/pt-br/training/paths/aspnet-core-web-app/',
    embeddable: false,
    tags: ['asp.net', 'web api', 'rest', 'microsoft learn'],
    professor: 'Microsoft Learn',
    preRequisitos: ['C#', 'Noções de REST'],
    objetivos: ['Criar APIs REST', 'Usar Minimal APIs'],
    tecnologiasRelacionadas: ['ASP.NET Core', 'C#', 'REST'],
    trilhas: ['apis-integracoes', 'desenvolvimento']
  },
  {
    id: 'mslearn-seguranca',
    titulo: 'Segurança e Identidade no Azure',
    descricao: 'Fundamentos de segurança, identidade e conformidade na Microsoft Learn, com foco no Azure.',
    categoria: 'microsoft-learn',
    plataforma: 'Microsoft Learn',
    autor: 'Microsoft',
    canal: 'Microsoft Learn',
    duracao: 'Módulos',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://learn.microsoft.com/pt-br/training/browse/?terms=security',
    embeddable: false,
    tags: ['seguranca', 'azure', 'identidade', 'microsoft learn'],
    professor: 'Microsoft Learn',
    preRequisitos: ['Nenhum'],
    objetivos: ['Entender segurança em nuvem', 'Conhecer identidade e acesso'],
    tecnologiasRelacionadas: ['Azure AD', 'Microsoft Entra ID'],
    trilhas: ['seguranca']
  }
];

// ══════════════════════════════════════════════════════════
// CISCO — Skills for All (cursos gratuitos)
// ══════════════════════════════════════════════════════════

export const cursosCisco: Curso[] = [
  {
    id: 'cisco-redes',
    titulo: 'Introdução à Redes de Computadores',
    descricao: 'Curso gratuito do Cisco Skills for All: fundamentos de redes, endereçamento IP, roteamento e comunicação.',
    categoria: 'cisco',
    plataforma: 'Cisco',
    autor: 'Cisco',
    canal: 'Cisco Skills for All',
    duracao: '40 horas',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://skillsforall.examscisco.com/cursos-gratuitos/',
    embeddable: false,
    tags: ['redes', 'tcp/ip', 'cisco', 'skills for all'],
    professor: 'Cisco Networking Academy',
    preRequisitos: ['Nenhum'],
    objetivos: ['Entender redes e IP', 'Conhecer roteamento e comunicação'],
    tecnologiasRelacionadas: ['TCP/IP', 'OSI', 'Roteadores'],
    trilhas: ['redes'],
    emDestaque: true
  },
  {
    id: 'cisco-ciberseguranca',
    titulo: 'Introdução à Cibersegurança',
    descricao: 'Curso gratuito do Cisco Skills for All: fundamentos de cibersegurança, ameaças e boas práticas de proteção.',
    categoria: 'cisco',
    plataforma: 'Cisco',
    autor: 'Cisco',
    canal: 'Cisco Skills for All',
    duracao: '15 horas',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://skillsforall.examscisco.com/cursos-gratuitos/',
    embeddable: false,
    tags: ['ciberseguranca', 'seguranca', 'cisco', 'skills for all'],
    professor: 'Cisco Networking Academy',
    preRequisitos: ['Nenhum'],
    objetivos: ['Entender ameaças cibernéticas', 'Aplicar boas práticas de segurança'],
    tecnologiasRelacionadas: ['Segurança', 'Redes'],
    trilhas: ['seguranca']
  },
  {
    id: 'cisco-python',
    titulo: 'Python Essentials',
    descricao: 'Curso gratuito do Cisco Skills for All em parceria com a Python Institute: do básico ao intermediário.',
    categoria: 'cisco',
    plataforma: 'Cisco',
    autor: 'Cisco',
    canal: 'Cisco Skills for All',
    duracao: '60 horas',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://skillsforall.examscisco.com/cursos-gratuitos/',
    embeddable: false,
    tags: ['python', 'programacao', 'cisco', 'skills for all'],
    professor: 'Python Institute',
    preRequisitos: ['Lógica de programação'],
    objetivos: ['Aprender Python', 'Resolver problemas com scripts'],
    tecnologiasRelacionadas: ['Python'],
    trilhas: ['fundamentos']
  }
];

// ══════════════════════════════════════════════════════════
// FUNDAÇÃO BRADESCO — Escola Virtual (cursos gratuitos)
// ══════════════════════════════════════════════════════════

export const cursosFundacaoBradesco: Curso[] = [
  {
    id: 'bradesco-excel',
    titulo: 'Excel Avançado',
    descricao: 'Curso gratuito da Fundação Bradesco: Excel do básico ao avançado, com fórmulas, tabelas e dashboards.',
    categoria: 'fundacao-bradesco',
    plataforma: 'Fundação Bradesco',
    autor: 'Fundação Bradesco',
    canal: 'Fundação Bradesco',
    duracao: 'Curso online',
    nivel: 'Intermediário',
    idioma: 'PT-BR',
    url: 'https://www.ev.org.br/areas-de-interesse',
    embeddable: false,
    tags: ['excel', 'planilhas', 'produtividade', 'fundacao bradesco'],
    professor: 'Fundação Bradesco',
    preRequisitos: ['Nenhum'],
    objetivos: ['Dominar fórmulas do Excel', 'Criar tabelas e dashboards'],
    tecnologiasRelacionadas: ['Excel'],
    trilhas: ['ferramentas']
  },
  {
    id: 'bradesco-lgpd',
    titulo: 'LGPD - Lei Geral de Proteção de Dados',
    descricao: 'Curso gratuito da Fundação Bradesco sobre a LGPD e a proteção de dados pessoais.',
    categoria: 'fundacao-bradesco',
    plataforma: 'Fundação Bradesco',
    autor: 'Fundação Bradesco',
    canal: 'Fundação Bradesco',
    duracao: 'Curso online',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.ev.org.br/areas-de-interesse',
    embeddable: false,
    tags: ['lgpd', 'seguranca', 'privacidade', 'fundacao bradesco'],
    professor: 'Fundação Bradesco',
    preRequisitos: ['Nenhum'],
    objetivos: ['Entender a LGPD', 'Aplicar proteção de dados'],
    tecnologiasRelacionadas: ['LGPD', 'Privacidade'],
    trilhas: ['seguranca']
  },
  {
    id: 'bradesco-seguranca-info',
    titulo: 'Segurança da Informação',
    descricao: 'Curso gratuito da Fundação Bradesco sobre fundamentos de segurança da informação e boas práticas.',
    categoria: 'fundacao-bradesco',
    plataforma: 'Fundação Bradesco',
    autor: 'Fundação Bradesco',
    canal: 'Fundação Bradesco',
    duracao: 'Curso online',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.ev.org.br/areas-de-interesse',
    embeddable: false,
    tags: ['seguranca', 'informacao', 'fundacao bradesco'],
    professor: 'Fundação Bradesco',
    preRequisitos: ['Nenhum'],
    objetivos: ['Entender segurança da informação', 'Aplicar boas práticas'],
    tecnologiasRelacionadas: ['Segurança'],
    trilhas: ['seguranca']
  },
  {
    id: 'bradesco-atendimento-publico',
    titulo: 'Atendimento ao Público',
    descricao: 'Curso gratuito da Fundação Bradesco sobre boas práticas de atendimento ao público, comunicação e relacionamento com o cliente.',
    categoria: 'atendimento',
    plataforma: 'Fundação Bradesco',
    autor: 'Fundação Bradesco',
    canal: 'Fundação Bradesco',
    duracao: 'Curso online',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://www.ev.org.br/cursos/atendimento-ao-publico',
    embeddable: false,
    tags: ['atendimento', 'comunicacao', 'cliente', 'fundacao bradesco'],
    professor: 'Fundação Bradesco',
    preRequisitos: ['Nenhum'],
    objetivos: ['Melhorar o atendimento ao público', 'Comunicar-se de forma eficaz'],
    tecnologiasRelacionadas: ['Atendimento', 'Comunicação'],
    trilhas: []
  }
];

// ══════════════════════════════════════════════════════════
// POSTMAN ACADEMY — Aprenda APIs de forma interativa
// ══════════════════════════════════════════════════════════

export const cursosPostman: Curso[] = [
  {
    id: 'postman-academy-apis',
    titulo: 'Postman Academy - APIs e Testes',
    descricao: 'Aprenda a criar, testar e automatizar APIs de forma interativa na Postman Academy, com badges verificáveis.',
    categoria: 'postman-academy',
    plataforma: 'Postman Academy',
    autor: 'Postman',
    canal: 'Postman Academy',
    duracao: 'Interativo',
    nivel: 'Iniciante',
    idioma: 'EN',
    url: 'https://academy.postman.com/',
    embeddable: false,
    tags: ['api', 'postman', 'testes', 'automacao'],
    professor: 'Postman Academy',
    preRequisitos: ['Noções de REST'],
    objetivos: ['Testar APIs', 'Criar coleções e automações'],
    tecnologiasRelacionadas: ['Postman', 'REST'],
    trilhas: ['apis-integracoes', 'ferramentas'],
    emDestaque: true
  }
];

// ══════════════════════════════════════════════════════════
// DOCUMENTAÇÃO / SITES — Cursos em páginas externas
// ══════════════════════════════════════════════════════════

export const cursosDocumentacao: Curso[] = [
  {
    id: 'ifsul-banco-dados',
    titulo: 'Banco de Dados - IFSUL (Mundi)',
    descricao: 'Material do portal Mundi do IFSUL com conteúdo didático sobre banco de dados, modelagem e SQL.',
    categoria: 'banco',
    plataforma: 'Documentação',
    autor: 'IFSUL - Mundi',
    canal: 'Mundi IFSUL',
    duracao: 'Portal educacional',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://mundi.ifsul.edu.br/portal/banco-de-dados.php',
    embeddable: false,
    tags: ['banco de dados', 'sql', 'modelagem', 'ifsul'],
    professor: 'Mundi IFSUL',
    preRequisitos: ['Nenhum'],
    objetivos: ['Entender conceitos de banco de dados', 'Aprender modelagem e SQL'],
    tecnologiasRelacionadas: ['SQL', 'Modelagem'],
    trilhas: ['banco-de-dados']
  },
  {
    id: 'sestsenat-atendimento',
    titulo: 'Comunicação Interpessoal e Atendimento ao Cliente',
    descricao: 'Curso gratuito do SEST SENAT sobre comunicação interpessoal e boas práticas de atendimento ao cliente.',
    categoria: 'atendimento',
    plataforma: 'Documentação',
    autor: 'SEST SENAT',
    canal: 'SEST SENAT',
    duracao: 'Curso online',
    nivel: 'Iniciante',
    idioma: 'PT-BR',
    url: 'https://digital.sestsenat.org.br/cursos/comunicacao-interpessoal-e-atendimento-ao-cliente-2',
    embeddable: false,
    tags: ['atendimento', 'comunicacao', 'cliente', 'sest senat'],
    professor: 'SEST SENAT',
    preRequisitos: ['Nenhum'],
    objetivos: ['Melhorar a comunicação interpessoal', 'Aprimorar o atendimento ao cliente'],
    tecnologiasRelacionadas: ['Atendimento', 'Comunicação'],
    trilhas: []
  }
];

export const todosCursos: Curso[] = [
  ...cursosAlura,
  ...cursosYouTube,
  ...cursosCursoEmVideo,
  ...cursosMicrosoftLearn,
  ...cursosCisco,
  ...cursosFundacaoBradesco,
  ...cursosPostman,
  ...cursosDocumentacao
];

export function buscarCursoPorId(id: string): Curso | undefined {
  return todosCursos.find(c => c.id === id);
}

export function listarCursosPorCategoria(categoriaId: string): Curso[] {
  return todosCursos.filter(c => c.categoria === categoriaId);
}

export function listarCursosPorTrilha(trilhaId: string): Curso[] {
  const trilha = trilhas.find(t => t.id === trilhaId);
  if (!trilha) return [];
  return trilha.cursoIds.map(id => buscarCursoPorId(id)).filter((c): c is Curso => !!c);
}

export function buscarCursos(termo: string): Curso[] {
  return todosCursos.filter(c =>
    buscarSingleTerm(termo, c.titulo, c.descricao, ...c.tags)
  );
}
